function summary = verify_fig10_blind_fullgrid_matlab(manifest_path, python_fullgrid_root, output_dir)
%VERIFY_FIG10_BLIND_FULLGRID_MATLAB Independently verify a six-route blind grid.
%
% This verifier is intentionally independent of the Python eigensolver.  It
% reads only a FIG10 blind-search manifest, its six MINIMAL_AUGMENTED_CORE_V1
% MAT bundles, and an already completed Python full-grid output root.  For
% every (l,j) in 0:30 x 0:66 it builds the 2*n+l+j state matrix directly in
% MATLAB, computes its eigenvalues, and compares rho/stable point by point.
%
% Forbidden inputs: plotted_data.mat, target/evaluation CSV files, PDFs, and
% the strict target evaluator.  No Python process or Python code is invoked.

    narginchk(3, 3);
    manifest_path = canonical_existing_file(manifest_path, '.json', 'manifest');
    python_fullgrid_root = canonical_existing_folder( ...
        python_fullgrid_root, 'python full-grid root');
    assert_safe_blind_path(manifest_path, 'manifest');
    assert_safe_blind_path(python_fullgrid_root, 'python full-grid root');

    output_dir = char(string(output_dir));
    assert(~isempty(strtrim(output_dir)), ...
        'Fig10MatlabVerify:EmptyOutputDirectory', 'output_dir不能为空。');
    if isfolder(output_dir)
        entries = dir(output_dir);
        names = setdiff({entries.name}, {'.', '..'});
        assert(isempty(names), 'Fig10MatlabVerify:OutputNotEmpty', ...
            '输出目录必须不存在或为空，拒绝覆盖：%s', output_dir);
    else
        [made, message] = mkdir(output_dir);
        assert(made, 'Fig10MatlabVerify:OutputCreateFailed', ...
            '无法创建输出目录%s：%s', output_dir, message);
    end
    output_dir = canonical_existing_folder(output_dir, 'output directory');
    assert_safe_blind_path(output_dir, 'output directory');

    paths = struct( ...
        'points', fullfile(output_dir, 'matlab_pointwise_comparison.csv'), ...
        'routes', fullfile(output_dir, 'matlab_route_summary.csv'), ...
        'summary', fullfile(output_dir, 'matlab_validation_summary.json'), ...
        'log', fullfile(output_dir, 'matlab_validation.log'), ...
        'hashes', fullfile(output_dir, 'artifact_hash_manifest.csv'));
    log_line(paths.log, 'MATLAB独立全网格复核开始。');
    log_line(paths.log, ['输入策略：只读盲算manifest、六个core MAT与已完成的' ...
        'Python full-grid；禁止目标数据、PDF、评价器和Python求解器。']);

    try
        manifest_sha256 = file_sha256(manifest_path);
        manifest = jsondecode(fileread(manifest_path));
        validate_manifest_header(manifest);
        routes = manifest.routes(:);
        validate_six_route_identity(routes);
        allowed_roots = json_string_list(manifest.allowed_bundle_roots, ...
            'allowed_bundle_roots');
        for root_index = 1:numel(allowed_roots)
            allowed_roots{root_index} = canonical_existing_folder( ...
                allowed_roots{root_index}, 'allowed bundle root');
            assert_safe_blind_path(allowed_roots{root_index}, ...
                'allowed bundle root');
        end

        run_summary_path = canonical_existing_file(fullfile( ...
            python_fullgrid_root, 'run_summary.json'), '.json', ...
            'python run summary');
        python_run_sha256 = file_sha256(run_summary_path);
        python_run = jsondecode(fileread(run_summary_path));
        validate_python_run_summary(python_run, manifest_sha256);

        package_count = numel(routes);
        packages = repmat(empty_package(), package_count, 1);
        source_tables = cell(package_count, 1);
        source_points_paths = cell(package_count, 1);
        source_points_sha256 = cell(package_count, 1);
        for route_index = 1:package_count
            route = routes(route_index);
            packages(route_index) = load_core_package( ...
                route, allowed_roots);
            [source_tables{route_index}, source_points_paths{route_index}, ...
                source_points_sha256{route_index}] = ...
                load_python_points(python_fullgrid_root, route, ...
                packages(route_index).dimension);
        end
        log_line(paths.log, sprintf([ ...
            '输入门通过：manifest SHA=%s；六个bundle SHA与字段均闭合；' ...
            'Python结果为PASS full-grid。'], manifest_sha256));

        l_expected = repelem((0:30).', 67);
        j_expected = repmat((0:66).', 31, 1);
        route_point_count = numel(l_expected);
        total_point_count = package_count * route_point_count;
        assert(total_point_count == 12462, ...
            'Fig10MatlabVerify:InternalPointCountMismatch', ...
            '六路线31x67必须为12462点。');

        route_index_all = repelem((1:package_count).', route_point_count);
        l_all = repmat(l_expected, package_count, 1);
        j_all = repmat(j_expected, package_count, 1);
        rho_matlab = NaN(total_point_count, 1);
        maximum_state_residual = NaN(total_point_count, 1);
        transition_reconstruction_error = NaN(total_point_count, 1);
        actual_root_count = zeros(total_point_count, 1);
        finite_code = false(total_point_count, 1);

        [parallel_enabled, worker_count] = ensure_parallel_pool();
        log_line(paths.log, sprintf( ...
            '开始MATLAB独立最小增广求解：points=%d，parallel=%d，workers=%d。', ...
            total_point_count, parallel_enabled, worker_count));
        wall_start = tic;
        if parallel_enabled
            parfor point_index = 1:total_point_count
                package = packages(route_index_all(point_index));
                [rho_matlab(point_index), ...
                    maximum_state_residual(point_index), ...
                    transition_reconstruction_error(point_index), ...
                    actual_root_count(point_index), ...
                    finite_code(point_index)] = solve_minimal_point( ...
                    package, l_all(point_index), j_all(point_index));
            end
        else
            for point_index = 1:total_point_count
                package = packages(route_index_all(point_index));
                [rho_matlab(point_index), ...
                    maximum_state_residual(point_index), ...
                    transition_reconstruction_error(point_index), ...
                    actual_root_count(point_index), ...
                    finite_code(point_index)] = solve_minimal_point( ...
                    package, l_all(point_index), j_all(point_index));
            end
        end
        elapsed_seconds = toc(wall_start);
        log_line(paths.log, sprintf( ...
            'MATLAB独立求解完成：points=%d，wall_seconds=%.6f。', ...
            total_point_count, elapsed_seconds));

        route_id = strings(total_point_count, 1);
        contract_id = strings(total_point_count, 1);
        method = strings(total_point_count, 1);
        division = zeros(total_point_count, 1);
        route_dimension = zeros(total_point_count, 1);
        route_point_order = zeros(total_point_count, 1);
        rho_python = NaN(total_point_count, 1);
        stable_python = false(total_point_count, 1);
        python_root_count = zeros(total_point_count, 1);
        python_overall_pass = false(total_point_count, 1);
        for route_index = 1:package_count
            first = (route_index - 1) * route_point_count + 1;
            last = first + route_point_count - 1;
            source = source_tables{route_index};
            package = packages(route_index);
            route_id(first:last) = string(package.route_id);
            contract_id(first:last) = string(package.contract_id);
            method(first:last) = string(package.method);
            division(first:last) = package.division;
            route_dimension(first:last) = package.dimension;
            route_point_order(first:last) = double(source.point_order);
            rho_python(first:last) = double(source.rho);
            stable_python(first:last) = logical(double(source.stable));
            python_root_count(first:last) = double(source.physical_root_count);
            python_overall_pass(first:last) = logical(double(source.overall_pass));
        end

        expected_root_count = 2 .* route_dimension + l_all + j_all;
        stable_matlab = rho_matlab < 1.0;
        rho_absolute_difference = abs(rho_matlab - rho_python);
        stable_mismatch = stable_matlab ~= stable_python;
        order_pass = actual_root_count == expected_root_count & ...
            python_root_count == expected_root_count;
        residual_pass = maximum_state_residual <= 1.0e-8;
        transition_pass = transition_reconstruction_error <= 1.0e-12;
        rho_pass = rho_absolute_difference <= 1.0e-9;
        point_pass = finite_code & isfinite(rho_matlab) & ...
            isfinite(rho_python) & python_overall_pass & order_pass & ...
            residual_pass & transition_pass & rho_pass & ~stable_mismatch;

        comparison = table(route_id, contract_id, division, method, ...
            route_dimension, route_point_order, l_all, j_all, ...
            expected_root_count, actual_root_count, python_root_count, ...
            rho_matlab, rho_python, rho_absolute_difference, ...
            stable_matlab, stable_python, stable_mismatch, ...
            maximum_state_residual, transition_reconstruction_error, ...
            finite_code, order_pass, residual_pass, transition_pass, ...
            rho_pass, python_overall_pass, point_pass, ...
            'VariableNames', {'route_id', 'contract_id', 'division', ...
            'method', 'route_dimension', 'point_order', 'l_samples', ...
            'j_samples', 'expected_root_count', 'matlab_root_count', ...
            'python_root_count', 'rho_matlab', 'rho_python', ...
            'rho_absolute_difference', 'stable_matlab', 'stable_python', ...
            'stable_mismatch', 'maximum_state_eigenpair_residual', ...
            'transition_reconstruction_error', 'finite_code', ...
            'order_pass', 'residual_pass', 'transition_pass', ...
            'rho_pass', 'python_overall_pass', 'overall_pass'});
        writetable(comparison, paths.points, 'Encoding', 'UTF-8');

        route_summary = build_route_summary(packages, comparison, ...
            source_points_paths, source_points_sha256);
        writetable(route_summary, paths.routes, 'Encoding', 'UTF-8');

        maximum_rho_difference = max(rho_absolute_difference);
        stable_mismatch_count = nnz(stable_mismatch);
        maximum_residual = max(maximum_state_residual);
        maximum_transition_error = max(transition_reconstruction_error);
        actual_total_root_count = sum(actual_root_count);
        expected_total_root_count = sum(expected_root_count);
        finite_point_count = nnz(finite_code & isfinite(rho_matlab));
        point_count_pass = total_point_count == 12462;
        finite_pass = finite_point_count == total_point_count;
        total_order_pass = actual_total_root_count == ...
            expected_total_root_count && all(order_pass);
        all_points_pass = all(point_pass);
        overall_pass = point_count_pass && finite_pass && ...
            total_order_pass && maximum_residual <= 1.0e-8 && ...
            maximum_transition_error <= 1.0e-12 && ...
            maximum_rho_difference <= 1.0e-9 && ...
            stable_mismatch_count == 0 && all_points_pass;

        if overall_pass
            status = 'PASS';
        else
            status = 'FAIL';
        end
        summary = struct( ...
            'schema_version', 'FIG10_MATLAB_INDEPENDENT_FULLGRID_V1', ...
            'status', status, ...
            'input_policy', ['BLIND_MANIFEST_CORE_MAT_AND_COMPLETED_' ...
                'PYTHON_POINTS_ONLY_NO_TARGET_NO_PDF_NO_PYTHON_SOLVER'], ...
            'solver', 'MATLAB_EIG_MINIMAL_AUGMENTED_2N_PLUS_L_PLUS_J', ...
            'manifest_path', manifest_path, ...
            'manifest_sha256', manifest_sha256, ...
            'python_fullgrid_root', python_fullgrid_root, ...
            'python_run_summary_sha256', python_run_sha256, ...
            'route_count', package_count, ...
            'point_count', total_point_count, ...
            'expected_point_count', 12462, ...
            'finite_point_count', finite_point_count, ...
            'actual_total_root_count', actual_total_root_count, ...
            'expected_total_root_count', expected_total_root_count, ...
            'maximum_rho_absolute_difference', maximum_rho_difference, ...
            'rho_tolerance', 1.0e-9, ...
            'stable_mismatch_count', stable_mismatch_count, ...
            'maximum_state_eigenpair_residual', maximum_residual, ...
            'state_residual_tolerance', 1.0e-8, ...
            'maximum_transition_reconstruction_error', ...
                maximum_transition_error, ...
            'transition_reconstruction_tolerance', 1.0e-12, ...
            'point_count_pass', point_count_pass, ...
            'finite_pass', finite_pass, ...
            'root_order_pass', total_order_pass, ...
            'rho_pass', maximum_rho_difference <= 1.0e-9, ...
            'stable_pass', stable_mismatch_count == 0, ...
            'residual_pass', maximum_residual <= 1.0e-8, ...
            'transition_reconstruction_pass', ...
                maximum_transition_error <= 1.0e-12, ...
            'all_points_pass', all_points_pass, ...
            'blind_calculation_only', true, ...
            'target_files_read', 0, ...
            'python_solver_invocations', 0, ...
            'route_summaries', table2struct(route_summary), ...
            'output_files', paths);
        write_json_utf8(paths.summary, summary);
        log_line(paths.log, sprintf([ ...
            '门禁完成：status=%s，points=%d，max_rho_diff=%.3e，' ...
            ['stable_mismatch=%d，max_residual=%.3e，' ...
             'max_transition_error=%.3e，root_order=%d。']], ...
            status, total_point_count, maximum_rho_difference, ...
            stable_mismatch_count, maximum_residual, ...
            maximum_transition_error, total_order_pass));
        log_line(paths.log, ...
            '科学输出已封闭；此行后不再改写日志，开始生成工件哈希清单。');

        verifier_path = [mfilename('fullpath'), '.m'];
        write_hash_manifest(paths.hashes, verifier_path, manifest_path, ...
            run_summary_path, packages, source_points_paths, paths);

        assert(overall_pass, 'Fig10MatlabVerify:ScientificGateFailed', ...
            ['MATLAB独立全网格复核失败：points=%d，max_rho_diff=%.3e，' ...
            'stable_mismatch=%d，max_residual=%.3e。'], ...
            total_point_count, maximum_rho_difference, ...
            stable_mismatch_count, maximum_residual);
        fprintf(['FIG10 MATLAB独立复核PASS：%d/%d点，max|rho_M-rho_P|=%.3e，' ...
            'stable差=%d，最大状态残差=%.3e。\n'], ...
            nnz(point_pass), total_point_count, maximum_rho_difference, ...
            stable_mismatch_count, maximum_residual);
    catch exception
        log_line(paths.log, sprintf('FAIL [%s] %s', ...
            exception.identifier, exception.message));
        rethrow(exception);
    end
end


function validate_manifest_header(manifest)
    required = {'schema_version', 'target_dependency', 'allowed_bundle_roots', ...
        'routes', 'sampling'};
    assert(all(isfield(manifest, required)), ...
        'Fig10MatlabVerify:ManifestFieldsMissing', ...
        '盲算manifest缺少必需字段。');
    assert(strcmp(char(string(manifest.schema_version)), ...
        'FIG10_BLIND_SEARCH_MANIFEST_V1'), ...
        'Fig10MatlabVerify:ManifestSchemaMismatch', ...
        '盲算manifest schema_version错误。');
    assert(strcmp(char(string(manifest.target_dependency)), ...
        'FORBIDDEN_BLIND_CALCULATION_ONLY'), ...
        'Fig10MatlabVerify:TargetFirewallMissing', ...
        'manifest未声明FORBIDDEN_BLIND_CALCULATION_ONLY。');
    assert(isfield(manifest.sampling, 'grid'), ...
        'Fig10MatlabVerify:GridMissing', 'manifest缺少sampling.grid。');
    grid = manifest.sampling.grid;
    assert(exact_integer(grid.l_min, 'l_min') == 0 && ...
        exact_integer(grid.l_max, 'l_max') == 30 && ...
        exact_integer(grid.j_min, 'j_min') == 0 && ...
        exact_integer(grid.j_max, 'j_max') == 66, ...
        'Fig10MatlabVerify:GridMismatch', ...
        '复核器只接受完整0:30 x 0:66盲算网格。');
end


function validate_six_route_identity(routes)
    assert(isstruct(routes) && numel(routes) == 6, ...
        'Fig10MatlabVerify:RouteCountMismatch', ...
        'manifest必须恰有六条路线。');
    required = {'route_id', 'contract_id', 'division', 'method', ...
        'dimension', 'operator_layout', 'bundle_path', 'bundle_sha256'};
    keys = strings(6, 1);
    route_ids = strings(6, 1);
    contracts = strings(6, 1);
    for route_index = 1:6
        route = routes(route_index);
        assert(all(isfield(route, required)), ...
            'Fig10MatlabVerify:RouteFieldsMissing', ...
            '第%d条路线缺少必需字段。', route_index);
        division = exact_integer(route.division, 'division');
        method = string(route.method);
        assert(ismember(method, ["Original", "Craig_Bampton", "Guyan"]), ...
            'Fig10MatlabVerify:MethodUnknown', '未知方法：%s', method);
        assert(division == 1 || division == 2, ...
            'Fig10MatlabVerify:DivisionUnknown', 'division必须为1或2。');
        assert(exact_integer(route.dimension, 'dimension') > 0, ...
            'Fig10MatlabVerify:DimensionInvalid', 'dimension必须为正整数。');
        assert(strcmp(char(string(route.operator_layout)), ...
            'MINIMAL_AUGMENTED_CORE_V1'), ...
            'Fig10MatlabVerify:OperatorLayoutMismatch', ...
            '路线%s不是MINIMAL_AUGMENTED_CORE_V1。', string(route.route_id));
        keys(route_index) = compose('D%d_%s', division, method);
        route_ids(route_index) = string(route.route_id);
        contracts(route_index) = string(route.contract_id);
    end
    expected = sort(["D1_Original"; "D1_Craig_Bampton"; "D1_Guyan"; ...
        "D2_Original"; "D2_Craig_Bampton"; "D2_Guyan"]);
    assert(isequal(sort(keys), expected), ...
        'Fig10MatlabVerify:RouteIdentityMismatch', ...
        '六路线必须覆盖两类划分与三种方法且各一次。');
    assert(numel(unique(route_ids)) == 6, ...
        'Fig10MatlabVerify:DuplicateRouteId', 'route_id必须唯一。');
    assert(numel(unique(contracts)) == 1, ...
        'Fig10MatlabVerify:MixedContracts', ...
        '一次复核的六条路线必须属于同一contract_id。');
end


function validate_python_run_summary(run_summary, manifest_sha256)
    required = {'schema_version', 'status', 'mode', 'route_count', ...
        'point_count', 'manifest_sha256', 'blind_calculation_only'};
    assert(all(isfield(run_summary, required)), ...
        'Fig10MatlabVerify:PythonSummaryFieldsMissing', ...
        'Python run_summary缺少必需字段。');
    assert(strcmp(char(string(run_summary.schema_version)), ...
        'FIG10_BLIND_SEARCH_RUN_V1') && ...
        strcmp(char(string(run_summary.status)), 'PASS') && ...
        strcmp(char(string(run_summary.mode)), 'full-grid'), ...
        'Fig10MatlabVerify:PythonRunNotComplete', ...
        'Python结果必须是PASS full-grid。');
    assert(exact_integer(run_summary.route_count, 'route_count') == 6 && ...
        exact_integer(run_summary.point_count, 'point_count') == 12462, ...
        'Fig10MatlabVerify:PythonRunCountMismatch', ...
        'Python结果必须恰有六路线、12462点。');
    assert(logical(run_summary.blind_calculation_only), ...
        'Fig10MatlabVerify:PythonBlindFlagMissing', ...
        'Python结果没有blind_calculation_only=true。');
    assert(strcmpi(char(string(run_summary.manifest_sha256)), manifest_sha256), ...
        'Fig10MatlabVerify:ManifestHashMismatch', ...
        'Python结果绑定的manifest SHA与当前manifest不一致。');
end


function package = load_core_package(route, allowed_roots)
    bundle_path = canonical_existing_file(route.bundle_path, '.mat', 'bundle');
    assert_safe_blind_path(bundle_path, 'bundle');
    assert(path_is_under_any_root(bundle_path, allowed_roots), ...
        'Fig10MatlabVerify:BundleOutsideAllowedRoots', ...
        'bundle不在manifest允许根下：%s', bundle_path);
    expected_sha = upper(char(string(route.bundle_sha256)));
    assert(numel(expected_sha) == 64 && ...
        all(ismember(expected_sha, ['0':'9', 'A':'F'])), ...
        'Fig10MatlabVerify:BundleHashMalformed', ...
        'manifest中的bundle_sha256格式错误。');
    actual_sha = file_sha256(bundle_path);
    assert(strcmp(actual_sha, expected_sha), ...
        'Fig10MatlabVerify:BundleHashMismatch', ...
        'bundle SHA-256不符：%s', bundle_path);

    required = {'dt', 'mass_term', 'base_zero', 'base_minus_one', ...
        'delay_left', 'delay_v_zero', 'delay_v_minus_one', ...
        'register_scales'};
    optional = {'route_dimension', 'dimension', 'division', 'method_code', ...
        'contract_id_code', 'bundle_schema_version', ...
        'shared_left_factor_relative_error', 'stage0_overall_pass_code'};
    inventory = whos('-file', bundle_path);
    names = {inventory.name};
    assert(all(ismember(required, names)), ...
        'Fig10MatlabVerify:BundleFieldsMissing', ...
        'bundle缺少FIG10_BLIND_CORE_V1必需字段：%s', bundle_path);
    selected_optional = optional(ismember(optional, names));
    loaded = load(bundle_path, required{:}, selected_optional{:});

    n = exact_integer(route.dimension, 'route.dimension');
    dt = finite_positive_scalar(loaded.dt, 'dt');
    mass_term = finite_real_matrix(loaded.mass_term, n, n, 'mass_term');
    base_zero = finite_real_matrix(loaded.base_zero, n, n, 'base_zero');
    base_minus_one = finite_real_matrix( ...
        loaded.base_minus_one, n, n, 'base_minus_one');
    delay_left = finite_real_matrix(loaded.delay_left, n, 2, 'delay_left');
    delay_v_zero = finite_real_matrix( ...
        loaded.delay_v_zero, 2, n, 'delay_v_zero');
    delay_v_minus_one = finite_real_matrix( ...
        loaded.delay_v_minus_one, 2, n, 'delay_v_minus_one');
    register_scales = double(loaded.register_scales(:));
    assert(numel(register_scales) == 2 && isreal(register_scales) && ...
        all(isfinite(register_scales)) && all(register_scales > 0), ...
        'Fig10MatlabVerify:RegisterScalesInvalid', ...
        'register_scales必须为两个严格正有限实数。');
    assert(rank(mass_term) == n, 'Fig10MatlabVerify:MassTermRankDeficient', ...
        'mass_term不满秩：%s', bundle_path);

    if isfield(loaded, 'route_dimension')
        assert(exact_integer(loaded.route_dimension, 'route_dimension') == n, ...
            'Fig10MatlabVerify:RouteDimensionMismatch', ...
            'MAT route_dimension与manifest不一致。');
    end
    if isfield(loaded, 'dimension')
        assert(exact_integer(loaded.dimension, 'dimension') == n, ...
            'Fig10MatlabVerify:DimensionMismatch', ...
            'MAT dimension与manifest不一致。');
    end
    division = exact_integer(route.division, 'route.division');
    if isfield(loaded, 'division')
        assert(exact_integer(loaded.division, 'division') == division, ...
            'Fig10MatlabVerify:DivisionMismatch', ...
            'MAT division与manifest不一致。');
    end
    method = char(string(route.method));
    if isfield(loaded, 'method_code')
        method_codes = struct('Original', 1, 'Guyan', 2, 'Craig_Bampton', 3);
        assert(exact_integer(loaded.method_code, 'method_code') == ...
            method_codes.(method), 'Fig10MatlabVerify:MethodCodeMismatch', ...
            'MAT method_code与manifest不一致。');
    end
    contract_id = char(string(route.contract_id));
    if isfield(loaded, 'contract_id_code') && ...
            ismember(contract_id, {'B1', 'B2', 'B3'})
        expected_contract_code = str2double(contract_id(2));
        assert(exact_integer(loaded.contract_id_code, 'contract_id_code') == ...
            expected_contract_code, ...
            'Fig10MatlabVerify:ContractCodeMismatch', ...
            'MAT contract_id_code与manifest不一致。');
    end
    if isfield(loaded, 'bundle_schema_version')
        assert(exact_integer(loaded.bundle_schema_version, ...
            'bundle_schema_version') == 1, ...
            'Fig10MatlabVerify:BundleSchemaMismatch', ...
            'bundle_schema_version必须为1。');
    end
    if isfield(loaded, 'shared_left_factor_relative_error')
        shared_error = double(loaded.shared_left_factor_relative_error);
        assert(isscalar(shared_error) && isfinite(shared_error) && ...
            shared_error <= 1.0e-10, ...
            'Fig10MatlabVerify:SharedLeftError', ...
            'shared_left_factor_relative_error超过1e-10。');
    end
    if isfield(loaded, 'stage0_overall_pass_code')
        assert(exact_integer(loaded.stage0_overall_pass_code, ...
            'stage0_overall_pass_code') == 1, ...
            'Fig10MatlabVerify:Stage0NotPass', ...
            'bundle的stage0_overall_pass_code不是1。');
    end

    package = empty_package();
    package.route_id = char(string(route.route_id));
    package.contract_id = contract_id;
    package.division = division;
    package.method = method;
    package.dimension = n;
    package.dt = dt;
    package.mass_term = mass_term;
    package.base_zero = base_zero;
    package.base_minus_one = base_minus_one;
    package.delay_left = delay_left;
    package.delay_v_zero = delay_v_zero;
    package.delay_v_minus_one = delay_v_minus_one;
    package.register_scales = register_scales;
    package.bundle_path = bundle_path;
    package.expected_bundle_sha256 = expected_sha;
    package.actual_bundle_sha256 = actual_sha;
end


function [source, points_path, points_sha256] = ...
        load_python_points(python_root, route, dimension)
    route_id = char(string(route.route_id));
    points_path = canonical_existing_file(fullfile(python_root, 'routes', ...
        route_id, 'full-grid', 'points.csv'), '.csv', 'python points');
    assert_safe_blind_path(points_path, 'python points');
    assert(path_is_under_any_root(points_path, {python_root}), ...
        'Fig10MatlabVerify:PythonPointsOutsideRoot', ...
        'points.csv不在指定Python full-grid根下。');
    points_sha256 = file_sha256(points_path);
    source = readtable(points_path, 'TextType', 'string', ...
        'VariableNamingRule', 'preserve');
    required = {'route_id', 'contract_id', 'division', 'method', ...
        'mode', 'point_order', 'l_samples', 'j_samples', ...
        'physical_root_count', 'rho', 'stable', 'overall_pass'};
    assert(all(ismember(required, source.Properties.VariableNames)), ...
        'Fig10MatlabVerify:PythonPointFieldsMissing', ...
        'Python points.csv缺少必需字段：%s', points_path);
    assert(height(source) == 2077, ...
        'Fig10MatlabVerify:PythonPointCountMismatch', ...
        '每条Python路线必须恰有2077点：%s', route_id);
    expected_l = repelem((0:30).', 67);
    expected_j = repmat((0:66).', 31, 1);
    expected_order = (1:2077).';
    assert(isequal(double(source.l_samples), expected_l) && ...
        isequal(double(source.j_samples), expected_j) && ...
        isequal(double(source.point_order), expected_order), ...
        'Fig10MatlabVerify:PythonPointOrderMismatch', ...
        'Python points.csv不是固定l外层、j内层的31x67顺序。');
    assert(all(string(source.route_id) == string(route_id)) && ...
        all(string(source.contract_id) == string(route.contract_id)) && ...
        all(double(source.division) == double(route.division)) && ...
        all(string(source.method) == string(route.method)) && ...
        all(string(source.mode) == "full-grid"), ...
        'Fig10MatlabVerify:PythonPointIdentityMismatch', ...
        'Python points.csv身份字段与manifest不一致。');
    expected_roots = 2 * dimension + expected_l + expected_j;
    assert(all(double(source.physical_root_count) == expected_roots), ...
        'Fig10MatlabVerify:PythonRootCountMismatch', ...
        'Python points.csv物理根数未满足2n+l+j。');
    assert(all(isfinite(double(source.rho))) && ...
        all(ismember(double(source.stable), [0, 1])) && ...
        all(double(source.overall_pass) == 1), ...
        'Fig10MatlabVerify:PythonPointGateFailed', ...
        'Python points.csv包含非有限rho、非法stable或失败点。');
end


function [rho, maximum_residual, transition_error, root_count, finite_code] = ...
        solve_minimal_point(package, l_samples, j_samples)
    n = package.dimension;
    delays = [double(l_samples), double(j_samples)];
    expected_order = 2 * n + sum(delays);
    augmented = zeros(expected_order, expected_order);
    augmented(1:n, 1:n) = -package.base_zero;
    augmented(1:n, n + (1:n)) = -package.base_minus_one;
    augmented(n + (1:n), 1:n) = eye(n);
    offset = 2 * n + 1;
    for channel = 1:2
        delay = delays(channel);
        u_vector = package.delay_left(:, channel);
        v_zero = package.delay_v_zero(channel, :);
        v_minus_one = package.delay_v_minus_one(channel, :);
        gamma = package.register_scales(channel);
        if delay == 0
            augmented(1:n, 1:n) = augmented(1:n, 1:n) - ...
                u_vector * v_zero;
            augmented(1:n, n + (1:n)) = ...
                augmented(1:n, n + (1:n)) - u_vector * v_minus_one;
        else
            registers = offset:(offset + delay - 1);
            augmented(1:n, registers(end)) = ...
                augmented(1:n, registers(end)) - u_vector * gamma;
            augmented(registers(1), 1:n) = v_zero / gamma;
            augmented(registers(1), n + (1:n)) = v_minus_one / gamma;
            if delay > 1
                augmented(registers(2:end), registers(1:end-1)) = ...
                    eye(delay - 1);
            end
            offset = offset + delay;
        end
    end
    assert(offset == expected_order + 1, ...
        'Fig10MatlabVerify:AugmentedIndexMismatch', ...
        '最小增广索引未闭合。');
    finite_matrix_code = isreal(augmented) && all(isfinite(augmented(:)));
    if ~finite_matrix_code
        rho = NaN;
        maximum_residual = Inf;
        transition_error = Inf;
        root_count = 0;
        finite_code = false;
        return;
    end

    % The native contract is a generalized state equation.  Only the top n
    % rows carry mass_term; the delay registers and previous-state rows have
    % an identity following operator.  Form the ordinary transition matrix
    % independently in MATLAB via left division before calling eig.
    transition = augmented;
    transition(1:n, :) = package.mass_term \ augmented(1:n, :);
    current_norm = norm(augmented, 'fro');
    reconstruction_top = package.mass_term * transition(1:n, :) - ...
        augmented(1:n, :);
    transition_error = norm(reconstruction_top, 'fro') / current_norm;
    finite_transition_code = all(isfinite(transition(:))) && ...
        isfinite(current_norm) && current_norm > 0.0 && ...
        isfinite(transition_error);
    if ~finite_transition_code
        rho = NaN;
        maximum_residual = Inf;
        transition_error = Inf;
        root_count = 0;
        finite_code = false;
        return;
    end

    [vectors, diagonal] = eig(transition);
    roots = diag(diagonal);
    root_count = numel(roots);
    finite_code = root_count == expected_order && ...
        all(isfinite(real(roots))) && all(isfinite(imag(roots))) && ...
        all(isfinite(real(vectors(:)))) && all(isfinite(imag(vectors(:))));
    if ~finite_code
        rho = NaN;
        maximum_residual = Inf;
        return;
    end
    following_times_vectors = vectors;
    following_times_vectors(1:n, :) = ...
        package.mass_term * vectors(1:n, :);
    residual_matrix = augmented * vectors - ...
        following_times_vectors .* roots.';
    vector_norm = vecnorm(vectors, 2, 1).';
    following_norm = sqrt(norm(package.mass_term, 'fro') ^ 2 + ...
        (expected_order - n));
    denominator = (current_norm + abs(roots) .* following_norm) .* ...
        vector_norm;
    state_residual = vecnorm(residual_matrix, 2, 1).' ./ ...
        max(denominator, realmin('double'));
    finite_code = finite_code && all(isfinite(state_residual));
    maximum_residual = max(state_residual);
    rho = max(abs(roots));
end


function route_summary = build_route_summary(packages, comparison, ...
        source_points_paths, source_points_sha256)
    route_count = numel(packages);
    route_id = strings(route_count, 1);
    contract_id = strings(route_count, 1);
    division = zeros(route_count, 1);
    method = strings(route_count, 1);
    dimension = zeros(route_count, 1);
    point_count = zeros(route_count, 1);
    matlab_stable_point_count = zeros(route_count, 1);
    python_stable_point_count = zeros(route_count, 1);
    maximum_rho_absolute_difference = NaN(route_count, 1);
    stable_mismatch_count = zeros(route_count, 1);
    maximum_state_eigenpair_residual = NaN(route_count, 1);
    maximum_transition_reconstruction_error = NaN(route_count, 1);
    minimum_rho_matlab = NaN(route_count, 1);
    maximum_rho_matlab = NaN(route_count, 1);
    bundle_sha256_match = false(route_count, 1);
    manifest_bundle_sha256 = strings(route_count, 1);
    actual_bundle_sha256 = strings(route_count, 1);
    python_points_path = strings(route_count, 1);
    python_points_sha256 = strings(route_count, 1);
    all_points_pass = false(route_count, 1);
    for route_index = 1:route_count
        package = packages(route_index);
        mask = comparison.route_id == string(package.route_id);
        route_id(route_index) = string(package.route_id);
        contract_id(route_index) = string(package.contract_id);
        division(route_index) = package.division;
        method(route_index) = string(package.method);
        dimension(route_index) = package.dimension;
        point_count(route_index) = nnz(mask);
        matlab_stable_point_count(route_index) = ...
            nnz(comparison.stable_matlab(mask));
        python_stable_point_count(route_index) = ...
            nnz(comparison.stable_python(mask));
        maximum_rho_absolute_difference(route_index) = ...
            max(comparison.rho_absolute_difference(mask));
        stable_mismatch_count(route_index) = ...
            nnz(comparison.stable_mismatch(mask));
        maximum_state_eigenpair_residual(route_index) = ...
            max(comparison.maximum_state_eigenpair_residual(mask));
        maximum_transition_reconstruction_error(route_index) = ...
            max(comparison.transition_reconstruction_error(mask));
        minimum_rho_matlab(route_index) = min(comparison.rho_matlab(mask));
        maximum_rho_matlab(route_index) = max(comparison.rho_matlab(mask));
        manifest_bundle_sha256(route_index) = ...
            string(package.expected_bundle_sha256);
        actual_bundle_sha256(route_index) = ...
            string(package.actual_bundle_sha256);
        bundle_sha256_match(route_index) = strcmp( ...
            package.expected_bundle_sha256, package.actual_bundle_sha256);
        python_points_path(route_index) = string(source_points_paths{route_index});
        python_points_sha256(route_index) = ...
            string(source_points_sha256{route_index});
        all_points_pass(route_index) = all(comparison.overall_pass(mask));
    end
    route_summary = table(route_id, contract_id, division, method, ...
        dimension, point_count, matlab_stable_point_count, ...
        python_stable_point_count, maximum_rho_absolute_difference, ...
        stable_mismatch_count, maximum_state_eigenpair_residual, ...
        maximum_transition_reconstruction_error, ...
        minimum_rho_matlab, maximum_rho_matlab, bundle_sha256_match, ...
        manifest_bundle_sha256, actual_bundle_sha256, ...
        python_points_path, python_points_sha256, all_points_pass);
end


function package = empty_package()
    package = struct('route_id', '', 'contract_id', '', 'division', 0, ...
        'method', '', 'dimension', 0, 'dt', NaN, 'mass_term', [], ...
        'base_zero', [], 'base_minus_one', [], 'delay_left', [], ...
        'delay_v_zero', [], 'delay_v_minus_one', [], ...
        'register_scales', [], 'bundle_path', '', ...
        'expected_bundle_sha256', '', 'actual_bundle_sha256', '');
end


function [enabled, workers] = ensure_parallel_pool()
    enabled = false;
    workers = 1;
    if ~(license('test', 'Distrib_Computing_Toolbox') && ...
            ~isempty(ver('parallel')))
        return;
    end
    try
        pool = gcp('nocreate');
        if isempty(pool)
            workers_requested = min(8, max(1, feature('numcores')));
            pool = parpool('threads', workers_requested);
        end
        enabled = true;
        workers = pool.NumWorkers;
    catch
        enabled = false;
        workers = 1;
    end
end


function values = json_string_list(raw, field_name)
    if ischar(raw)
        values = {raw};
    elseif isstring(raw)
        values = cellstr(raw(:));
    elseif iscell(raw)
        values = cellfun(@(value) char(string(value)), raw(:), ...
            'UniformOutput', false);
    else
        error('Fig10MatlabVerify:JsonStringListInvalid', ...
            '%s必须为JSON字符串数组。', field_name);
    end
    assert(~isempty(values) && all(~cellfun(@isempty, values)), ...
        'Fig10MatlabVerify:JsonStringListEmpty', ...
        '%s不能为空。', field_name);
end


function value = exact_integer(raw, field_name)
    value = double(raw);
    assert(isscalar(value) && isreal(value) && isfinite(value) && ...
        value == round(value), 'Fig10MatlabVerify:IntegerFieldInvalid', ...
        '%s必须为有限整数。', field_name);
end


function value = finite_positive_scalar(raw, field_name)
    value = double(raw);
    assert(isscalar(value) && isreal(value) && isfinite(value) && value > 0, ...
        'Fig10MatlabVerify:PositiveScalarInvalid', ...
        '%s必须为严格正有限实数。', field_name);
end


function value = finite_real_matrix(raw, rows, columns, field_name)
    value = double(raw);
    assert(isreal(value) && isequal(size(value), [rows, columns]) && ...
        all(isfinite(value(:))), 'Fig10MatlabVerify:MatrixFieldInvalid', ...
        '%s必须为%d×%d有限实矩阵。', field_name, rows, columns);
end


function path_value = canonical_existing_file(raw, extension, role)
    path_value = char(string(raw));
    assert(isfile(path_value), 'Fig10MatlabVerify:InputFileMissing', ...
        '%s不存在：%s', role, path_value);
    [~, ~, actual_extension] = fileparts(path_value);
    assert(strcmpi(actual_extension, extension), ...
        'Fig10MatlabVerify:InputExtensionMismatch', ...
        '%s扩展名必须为%s：%s', role, extension, path_value);
    path_value = canonical_path(path_value);
end


function path_value = canonical_existing_folder(raw, role)
    path_value = char(string(raw));
    assert(isfolder(path_value), 'Fig10MatlabVerify:InputFolderMissing', ...
        '%s不存在：%s', role, path_value);
    path_value = canonical_path(path_value);
end


function result = canonical_path(path_value)
    file_object = javaObject('java.io.File', char(path_value));
    result = char(file_object.getCanonicalPath());
end


function inside = path_is_under_any_root(path_value, roots)
    normalized_path = lower(canonical_path(path_value));
    inside = false;
    for root_index = 1:numel(roots)
        normalized_root = lower(canonical_path(roots{root_index}));
        if strcmp(normalized_path, normalized_root) || ...
                startsWith(normalized_path, [normalized_root, filesep])
            inside = true;
            return;
        end
    end
end


function assert_safe_blind_path(path_value, role)
    normalized = lower(strrep(char(path_value), '/', filesep));
    forbidden = { ...
        'plotted_data.mat', ...
        [filesep, 'evaluation', filesep], ...
        'strict_target_evaluator', ...
        '目标csv', ...
        '论文边界csv'};
    for token_index = 1:numel(forbidden)
        assert(~contains(normalized, lower(forbidden{token_index})), ...
            'Fig10MatlabVerify:ForbiddenTargetPath', ...
            '%s命中禁止目标路径标记%s：%s', ...
            role, forbidden{token_index}, path_value);
    end
    [~, ~, extension] = fileparts(path_value);
    assert(~strcmpi(extension, '.pdf'), ...
        'Fig10MatlabVerify:ForbiddenPdf', ...
        '%s不得为PDF：%s', role, path_value);
end


function log_line(path_value, message)
    file_id = fopen(path_value, 'a', 'n', 'UTF-8');
    assert(file_id >= 0, 'Fig10MatlabVerify:LogOpenFailed', ...
        '无法写入日志：%s', path_value);
    cleanup = onCleanup(@() fclose(file_id));
    fprintf(file_id, '%s | %s\n', char(datetime('now', ...
        'Format', 'yyyy-MM-dd HH:mm:ss.SSS')), message);
    clear cleanup;
end


function hash_value = file_sha256(path_value)
    file_id = fopen(path_value, 'rb');
    assert(file_id >= 0, 'Fig10MatlabVerify:HashOpenFailed', ...
        '无法读取待哈希文件：%s', path_value);
    cleanup = onCleanup(@() fclose(file_id));
    digest = java.security.MessageDigest.getInstance('SHA-256');
    while true
        bytes = fread(file_id, 1024 * 1024, '*uint8');
        if isempty(bytes)
            break;
        end
        digest.update(typecast(bytes(:), 'int8'));
    end
    raw = typecast(digest.digest(), 'uint8');
    hash_value = upper(reshape(dec2hex(raw, 2).', 1, []));
    clear cleanup;
end


function write_hash_manifest(path_value, verifier_path, manifest_path, ...
        run_summary_path, packages, source_points_paths, output_paths)
    roles = {'verifier_source'; 'blind_manifest'; 'python_run_summary'};
    file_paths = {canonical_path(verifier_path); manifest_path; run_summary_path};
    for package_index = 1:numel(packages)
        roles{end + 1, 1} = 'operator_bundle'; %#ok<AGROW>
        file_paths{end + 1, 1} = packages(package_index).bundle_path; %#ok<AGROW>
        roles{end + 1, 1} = 'python_points'; %#ok<AGROW>
        file_paths{end + 1, 1} = source_points_paths{package_index}; %#ok<AGROW>
    end
    output_names = {'points', 'routes', 'summary', 'log'};
    for output_index = 1:numel(output_names)
        roles{end + 1, 1} = 'matlab_output'; %#ok<AGROW>
        file_paths{end + 1, 1} = canonical_path( ...
            output_paths.(output_names{output_index})); %#ok<AGROW>
    end
    sha256 = cellfun(@file_sha256, file_paths, 'UniformOutput', false);
    bytes = cellfun(@file_bytes, file_paths);
    status = repmat({'HASHED'}, numel(file_paths), 1);
    output = table(string(roles), string(file_paths), bytes, ...
        string(sha256), string(status), ...
        'VariableNames', {'role', 'path', 'bytes', 'sha256', 'status'});
    writetable(output, path_value, 'Encoding', 'UTF-8');
end


function bytes = file_bytes(path_value)
    information = dir(path_value);
    assert(isscalar(information), 'Fig10MatlabVerify:FileBytesFailed', ...
        '无法唯一读取文件大小：%s', path_value);
    bytes = information.bytes;
end


function write_json_utf8(path_value, value)
    write_text_utf8(path_value, jsonencode(value, 'PrettyPrint', true));
end


function write_text_utf8(path_value, text_value)
    file_id = fopen(path_value, 'w', 'n', 'UTF-8');
    assert(file_id >= 0, 'Fig10MatlabVerify:TextOpenFailed', ...
        '无法写入文本：%s', path_value);
    cleanup = onCleanup(@() fclose(file_id));
    bytes = unicode2native(char(text_value), 'UTF-8');
    count = fwrite(file_id, bytes, 'uint8');
    assert(count == numel(bytes), 'Fig10MatlabVerify:TextWriteFailed', ...
        '文本未完整写入：%s', path_value);
    clear cleanup;
end
