function test_solve_board20_author_poles()
%TEST_SOLVE_BOARD20_AUTHOR_POLES Local unit and frozen-route pilot tests.
% This file never scans a grid and never writes scientific result files.

    fprintf('TEST 1/5: ORI_DIV1_H_RIGHT known Laurent roots...\n');
    n = 6;
    matrices = base_test_matrices(n);
    matrices.K1 = eye(n);
    matrices.K2(1, 1) = -0.25;
    matrices.K2(6, 6) = -0.36;
    result = solve_board20_author_poles( ...
        matrices, 'ORI_DIV1_H_RIGHT', 1, 2);
    assert(strcmp(result.point_status, 'PASS'), result.diagnostic.message);
    expected = sort_complex([0.25; 0.6; -0.6]);
    actual = sort_complex(result.poles);
    assert(numel(actual) == numel(expected));
    assert(max(abs(actual - expected)) <= 1e-10);
    assert(result.removed_zero_root_count == 9);
    assert(abs(result.rho - 0.6) <= 1e-12);
    assert(result.stable && ~result.critical);

    fprintf('TEST 2/5: GUYAN_DIV1_H_LEFT direct formula orientation...\n');
    n = 5;
    matrices = base_test_matrices(n);
    matrices.K1 = [ ...
        2.0, 0.3, 0.2, 0.0, 0.0; ...
       -0.4, 1.5, 0.1, 0.1, 0.0; ...
        0.2, 0.1, 1.8, 0.2, 0.1; ...
        0.1, 0.0, 0.3, 1.6, 0.2; ...
        0.0, 0.2, 0.1, 0.1, 1.7];
    matrices.K2 = [ ...
       -0.8, 0.4, 0.2, 0.0, 0.1; ...
        0.3,-0.7, 0.1, 0.2, 0.0; ...
        0.1, 0.2,-0.1, 0.1, 0.0; ...
        0.0, 0.1, 0.2,-0.2, 0.1; ...
        0.2, 0.0, 0.1, 0.2,-0.1];
    result = solve_board20_author_poles( ...
        matrices, 'GUYAN_DIV1_H_LEFT', 1, 2);
    assert(strcmp(result.point_status, 'PASS'), result.diagnostic.message);
    correct_residuals = zeros(numel(result.poles), 1);
    wrong_residuals = zeros(numel(result.poles), 1);
    for k = 1:numel(result.poles)
        z = result.poles(k);
        H = zeros(n);
        H(1, 1) = z^-1;
        H(2, 2) = z^-2;
        correct_matrix = matrices.K1 + H * matrices.K2;
        wrong_matrix = matrices.K1 + matrices.K2 * H;
        correct_residuals(k) = min(svd(correct_matrix)) / ...
            (norm(matrices.K1, 'fro') + norm(H * matrices.K2, 'fro'));
        wrong_residuals(k) = min(svd(wrong_matrix)) / ...
            (norm(matrices.K1, 'fro') + norm(matrices.K2 * H, 'fro'));
    end
    assert(max(correct_residuals) <= 1e-8);
    assert(max(wrong_residuals) >= 1e-4, ...
        'The test matrices did not distinguish H-left from H-right.');

    fprintf('TEST 3/5: DIV2 feedback remains outside H...\n');
    n = 5;
    matrices = base_test_matrices(n);
    matrices.K1 = eye(n);
    matrices.K2(1, 1) = -0.4;
    matrices.K2(2, 2) = -0.45;
    matrices.S = [eye(2), zeros(2, n-2)];
    matrices.DeltaC = zeros(2);
    matrices.DeltaK = diag([1, 3]);
    result = solve_board20_author_poles( ...
        matrices, 'DIV2_H_LEFT_FEEDBACK_OUTSIDE', 1, 2);
    assert(strcmp(result.point_status, 'PASS'), result.diagnostic.message);
    expected = sort_complex([0.2; sqrt(0.45/4); -sqrt(0.45/4)]);
    actual = sort_complex(result.poles);
    assert(numel(actual) == numel(expected));
    assert(max(abs(actual - expected)) <= 1e-10);
    assert(result.removed_zero_root_count == 7);
    assert(result.stable && ~result.critical);

    fprintf('TEST 4/5: failures return evidence; invalid contracts throw...\n');
    zero_matrices = base_test_matrices(5);
    failed = solve_board20_author_poles( ...
        zero_matrices, 'GUYAN_DIV1_H_LEFT', 0, 0);
    assert(strcmp(failed.point_status, 'FAIL'));
    assert(strcmp(failed.diagnostic.identifier, ...
        'board20:solver:IdenticallyZero'));
    assert(~failed.stable && ~failed.critical);

    threw = false;
    try
        solve_board20_author_poles(matrices, 'INFER_A_ROUTE', 0, 0);
    catch ME
        threw = strcmp(ME.identifier, 'board20:solver:InvalidRouteFormula');
    end
    assert(threw, 'Invalid route_formula did not throw the required contract error.');

    fprintf('TEST 5/5: frozen author zero-delay pilot rho values...\n');
    run_frozen_author_pilots();

    fprintf('ALL_TESTS_PASS\n');
end


function matrices = base_test_matrices(n)
    matrices = struct();
    matrices.M = zeros(n);
    matrices.C1 = zeros(n);
    matrices.K1 = zeros(n);
    matrices.C2 = zeros(n);
    matrices.K2 = zeros(n);
    matrices.al = eye(n);
    matrices.dt = 1;
end


function sorted = sort_complex(values)
    table = [real(values(:)), imag(values(:))];
    [~, order] = sortrows(table, [1, 2]);
    sorted = values(order);
end


function run_frozen_author_pilots()
    code_dir = fileparts(mfilename('fullpath'));
    board_dir = fileparts(code_dir);
    runs_dir = fullfile(board_dir, 'outputs', 'step2_runs');

    guyan_points = [0,0; 1,0; 0,1; 10,10; 20,20];
    guyan_targets = [ ...
        0.9991641004386277; ...
        0.9991672091602677; ...
        0.9992082795812388; ...
        1.0055004806976395; ...
        1.0055237300587734];
    alternate_targets = [ ...
        0.9988480464511478; ...
        0.9987026845106959; ...
        0.9999721424250212; ...
        1.0279567507912262; ...
        1.0207541887116507];
    div2_points = [0,0; 1,0; 0,1; 10,10; 20,20; 25,40; 25,60; 5,66];
    div2_targets = [ ...
        0.9869383552734836; ...
        0.9866922874900600; ...
        0.9884578543948703; ...
        1.0231638014417315; ...
        1.0177831304339464; ...
        1.0155164854102730; ...
        1.0312488778465467; ...
        1.0341351653420907];

    cases = { ...
        fullfile(runs_dir, 'main_ori_div1', 'original_mlx', 'rep03', ...
            'workspace', 'workspace_complete.mat'), ...
        'ORI_DIV1_H_RIGHT', false, [0,0], 0.9991697741274308; ...
        fullfile(runs_dir, 'main_guyan_div1', 'original_mlx', 'rep03', ...
            'workspace', 'workspace_complete.mat'), ...
        'GUYAN_DIV1_H_LEFT', false, guyan_points, guyan_targets; ...
        fullfile(runs_dir, 'alt_guyan_div1_stable_full_ps3', ...
            'original_mlx', 'rep01', 'workspace', 'workspace_complete.mat'), ...
        'GUYAN_DIV1_H_LEFT', false, guyan_points, alternate_targets; ...
        fullfile(runs_dir, 'main_ori_div2', 'original_mlx', 'rep03', ...
            'workspace', 'workspace_complete.mat'), ...
        'DIV2_H_LEFT_FEEDBACK_OUTSIDE', true, div2_points, div2_targets; ...
        fullfile(runs_dir, 'main_guyan_div2', 'original_mlx', 'rep03', ...
            'workspace', 'workspace_complete.mat'), ...
        'DIV2_H_LEFT_FEEDBACK_OUTSIDE', true, div2_points, div2_targets};

    for case_index = 1:size(cases, 1)
        source = cases{case_index, 1};
        route = cases{case_index, 2};
        needs_feedback = cases{case_index, 3};
        points = cases{case_index, 4};
        targets = cases{case_index, 5};
        assert(isfile(source), 'Frozen author workspace is missing: %s', source);

        if needs_feedback
            requested = {'C1', 'K1', 'C2', 'K2', 'al', 'dt', ...
                'stab', 'MRren', 'S', 'DeltaC', 'DeltaK'};
        elseif strcmp(route, 'ORI_DIV1_H_RIGHT')
            requested = {'C1', 'K1', 'C2', 'K2', 'al', 'dt', ...
                'stab', 'MRrt'};
        else
            requested = {'C1', 'K1', 'C2', 'K2', 'al', 'dt', ...
                'stab', 'MRren'};
        end
        workspace = load(source, requested{:});

        matrices = struct( ...
            'M', select_mass(workspace, route), ...
            'C1', workspace.C1, ...
            'K1', workspace.K1, ...
            'C2', workspace.C2, ...
            'K2', workspace.K2, ...
            'al', workspace.al, ...
            'dt', workspace.dt);
        if needs_feedback
            matrices.S = workspace.S;
            matrices.DeltaC = workspace.DeltaC;
            matrices.DeltaK = workspace.DeltaK;
        end

        for point_index = 1:size(points, 1)
            l = points(point_index, 1);
            j = points(point_index, 2);
            result = solve_board20_author_poles(matrices, route, l, j);
            assert(strcmp(result.point_status, 'PASS'), ...
                '%s pilot (%d,%d) failed: %s', ...
                route, l, j, result.diagnostic.message);
            author_rho = workspace.stab(l+1, j+1);
            target_rho = targets(point_index);
            assert(isfinite(author_rho) && author_rho > 0, ...
                '%s frozen author stab(%d,%d) is not a populated rho.', ...
                route, l+1, j+1);
            assert(abs(author_rho - target_rho) <= 1e-12, ...
                '%s frozen author rho differs from preregistered target.', route);
            rho_error = abs(result.rho - target_rho);
            fprintf(['  %s (%d,%d): solver=%.17g author=%.17g ', ...
                'abs_error=%.3g degree=%d order=%d\n'], ...
                route, l, j, result.rho, target_rho, rho_error, ...
                result.poly_degree, result.diagnostic.linearization_order);
            assert(rho_error <= 1e-8, ...
                '%s pilot (%d,%d) rho error %.17g exceeds 1e-8.', ...
                route, l, j, rho_error);
        end
    end
end


function mass = select_mass(workspace, route)
    if strcmp(route, 'ORI_DIV1_H_RIGHT')
        mass = workspace.MRrt;
    else
        mass = workspace.MRren;
    end
end
