function evidence = verify_board20_step8e_matlab_repeatability()
%VERIFY_BOARD20_STEP8E_MATLAB_REPEATABILITY 保存现有第一轮并真实运行第二轮。
% 动态墙钟/日期不进入证据。MAT-v7.3容器字节哈希只记录不设相等门；
% 确定性硬门使用规范化科学数组SHA和确定性CSV/JSON的文件SHA。

    wrapper_path = [mfilename('fullpath'), '.m'];
    code_dir = fileparts(wrapper_path);
    board_dir = fileparts(code_dir);
    output_dir = fullfile(board_dir, 'outputs', ...
        'step8e_四候选全网格', 'matlab');
    main_script_path = fullfile(code_dir, ...
        'run_board20_step8e_fullgrid_matlab.m');
    paths = struct( ...
        'summary', fullfile(output_dir, 'MATLAB步骤8E摘要.json'), ...
        'points', fullfile(output_dir, 'MATLAB全网格逐点摘要.csv'), ...
        'certificate', fullfile(output_dir, 'MATLAB边界证书.csv'), ...
        'arrays', fullfile(output_dir, 'MATLAB全网格科学数组.mat'), ...
        'admission', fullfile(output_dir, 'MATLAB候选准入门禁.csv'), ...
        'sentinel', fullfile(output_dir, 'MATLAB固定性能哨兵.csv'), ...
        'run1', fullfile(output_dir, 'MATLAB确定性_第一轮科学摘要.json'), ...
        'run2', fullfile(output_dir, 'MATLAB确定性_第二轮科学摘要.json'), ...
        'csv', fullfile(output_dir, 'MATLAB两轮确定性证据.csv'), ...
        'json', fullfile(output_dir, 'MATLAB两轮确定性证据.json'));
    assert(isfolder(output_dir) && isfile(main_script_path), ...
        'Board20Step8ERepeatability:PathMissing', ...
        '步骤8E输出目录或主脚本不存在。');
    stale = {paths.run1, paths.run2, paths.csv, paths.json};
    for index = 1:numel(stale)
        if isfile(stale{index})
            delete(stale{index});
        end
    end

    main_script_sha = file_sha256(main_script_path);
    wrapper_script_sha = file_sha256(wrapper_path);
    run1 = capture_scientific_run('run1', paths, main_script_sha, ...
        wrapper_script_sha);
    write_json_utf8(paths.run1, run1);

    run_board20_step8e_fullgrid_matlab('full');

    assert(strcmp(main_script_sha, file_sha256(main_script_path)), ...
        'Board20Step8ERepeatability:MainScriptChanged', ...
        '两轮之间主脚本SHA发生改变。');
    assert(strcmp(wrapper_script_sha, file_sha256(wrapper_path)), ...
        'Board20Step8ERepeatability:WrapperScriptChanged', ...
        '两轮之间确定性包装器SHA发生改变。');
    run2 = capture_scientific_run('run2', paths, main_script_sha, ...
        wrapper_script_sha);
    write_json_utf8(paths.run2, run2);

    point_csv_equal = strcmp(run1.point_csv_sha256, run2.point_csv_sha256);
    certificate_csv_equal = strcmp(run1.certificate_csv_sha256, ...
        run2.certificate_csv_sha256);
    normalized_science_equal = strcmp(run1.scientific_array_sha256, ...
        run2.scientific_array_sha256);
    summary_json_equal = strcmp(run1.summary_json_sha256, ...
        run2.summary_json_sha256);
    admission_csv_equal = strcmp(run1.admission_csv_sha256, ...
        run2.admission_csv_sha256);
    sentinel_csv_equal = strcmp(run1.sentinel_csv_sha256, ...
        run2.sentinel_csv_sha256);
    scalar_contract_equal = isequal( ...
        scientific_scalar_vector(run1), scientific_scalar_vector(run2));
    arrays_container_equal_not_required = strcmp( ...
        run1.arrays_container_sha256, run2.arrays_container_sha256);
    all_required_equal = point_csv_equal && certificate_csv_equal && ...
        normalized_science_equal && summary_json_equal && ...
        admission_csv_equal && sentinel_csv_equal && scalar_contract_equal && ...
        run1.all_scientific_gates_pass && run2.all_scientific_gates_pass;

    run_table = struct2table([run1; run2]);
    writetable(run_table, paths.csv, 'Encoding', 'UTF-8');
    evidence = struct( ...
        'schema', 'board20-step8e-matlab-two-run-determinism-v1', ...
        'run_count', 2, ...
        'dynamic_values_policy', ...
            'TIMING_DATETIME_LOGS_EXCLUDED_FROM_ALL_DETERMINISM_GATES', ...
        'mat_container_policy', ...
            'V73_CONTAINER_SHA_RECORDED_NOT_REQUIRED_USE_NORMALIZED_SCIENCE_SHA', ...
        'main_script_sha256', main_script_sha, ...
        'wrapper_script_sha256', wrapper_script_sha, ...
        'point_csv_equal', point_csv_equal, ...
        'certificate_csv_equal', certificate_csv_equal, ...
        'normalized_scientific_array_equal', normalized_science_equal, ...
        'summary_json_equal', summary_json_equal, ...
        'admission_csv_equal', admission_csv_equal, ...
        'sentinel_csv_equal', sentinel_csv_equal, ...
        'scientific_scalar_contract_equal', scalar_contract_equal, ...
        'arrays_container_equal_not_required', ...
            arrays_container_equal_not_required, ...
        'all_required_equal', all_required_equal, ...
        'run1_record_path', paths.run1, ...
        'run2_record_path', paths.run2, ...
        'run_csv_path', paths.csv, ...
        'run1', run1, 'run2', run2);
    write_json_utf8(paths.json, evidence);
    if ~all_required_equal
        error('Board20Step8ERepeatability:DeterminismGateFailed', ...
            '步骤8E MATLAB两轮规范化科学工件不一致；证据已保留。');
    end
    fprintf(['步骤8E MATLAB两轮确定性通过：science=%s，points=%s，' ...
        'certificate=%s。\n'], run2.scientific_array_sha256, ...
        run2.point_csv_sha256, run2.certificate_csv_sha256);
end


function record = capture_scientific_run(run_id, paths, main_sha, wrapper_sha)
    required = {paths.summary, paths.points, paths.certificate, ...
        paths.arrays, paths.admission, paths.sentinel};
    assert(all(cellfun(@isfile, required)), ...
        'Board20Step8ERepeatability:RunFilesMissing', ...
        '%s科学输出不完整。', run_id);
    summary = jsondecode(fileread(paths.summary));
    assert(summary.point_count == 49848 && ...
        summary.total_physical_root_count == 3356432 && ...
        summary.all_points_pass && summary.certificate_pass && ...
        summary.maximum_state_matrix_relative_residual <= 1e-8 && ...
        summary.certificate_maximum_state_residual <= 1e-8 && ...
        summary.certificate_maximum_laurent_residual <= 1e-8 && ...
        summary.certificate_maximum_polynomial_residual <= 1e-8, ...
        'Board20Step8ERepeatability:ScientificGateFailed', ...
        '%s未通过科学门，停止第二轮/确定性认领。', run_id);
    point_sha = file_sha256(paths.points);
    certificate_sha = file_sha256(paths.certificate);
    assert(strcmpi(point_sha, summary.point_csv_sha256) && ...
        strcmpi(certificate_sha, summary.certificate_csv_sha256), ...
        'Board20Step8ERepeatability:SummaryHashMismatch', ...
        '%s摘要内CSV哈希与实际文件不符。', run_id);
    record = struct( ...
        'run_id', run_id, ...
        'point_count', summary.point_count, ...
        'total_physical_root_count', summary.total_physical_root_count, ...
        'stable_point_count', summary.stable_point_count, ...
        'critical_point_count', summary.critical_point_count, ...
        'unstable_point_count', summary.unstable_point_count, ...
        'maximum_state_residual', ...
            summary.maximum_state_matrix_relative_residual, ...
        'certificate_point_count', summary.certificate_point_count, ...
        'certificate_root_count', summary.certificate_root_count, ...
        'certificate_maximum_state_residual', ...
            summary.certificate_maximum_state_residual, ...
        'certificate_maximum_laurent_residual', ...
            summary.certificate_maximum_laurent_residual, ...
        'certificate_maximum_polynomial_residual', ...
            summary.certificate_maximum_polynomial_residual, ...
        'certificate_maximum_independent_rho_difference', ...
            summary.certificate_maximum_independent_rho_difference, ...
        'all_scientific_gates_pass', logical(summary.all_points_pass && ...
            summary.certificate_pass), ...
        'main_script_sha256', main_sha, ...
        'wrapper_script_sha256', wrapper_sha, ...
        'point_csv_sha256', point_sha, ...
        'certificate_csv_sha256', certificate_sha, ...
        'scientific_array_sha256', char(summary.scientific_array_sha256), ...
        'summary_json_sha256', file_sha256(paths.summary), ...
        'admission_csv_sha256', file_sha256(paths.admission), ...
        'sentinel_csv_sha256', file_sha256(paths.sentinel), ...
        'arrays_container_sha256', file_sha256(paths.arrays));
end


function values = scientific_scalar_vector(record)
    values = [record.point_count; record.total_physical_root_count; ...
        record.stable_point_count; record.critical_point_count; ...
        record.unstable_point_count; record.maximum_state_residual; ...
        record.certificate_point_count; record.certificate_root_count; ...
        record.certificate_maximum_state_residual; ...
        record.certificate_maximum_laurent_residual; ...
        record.certificate_maximum_polynomial_residual; ...
        record.certificate_maximum_independent_rho_difference];
end


function hash_value = file_sha256(path_value)
    file_id = fopen(path_value, 'rb');
    assert(file_id >= 0, 'Board20Step8ERepeatability:HashOpenFailed', ...
        '无法读取待哈希文件：%s', path_value);
    cleanup = onCleanup(@() fclose(file_id));
    digest = java.security.MessageDigest.getInstance('SHA-256');
    while true
        bytes = fread(file_id, 1024 * 1024, '*uint8');
        if isempty(bytes)
            break;
        end
        digest.update(typecast(bytes(:), 'int8'));
    end
    raw = typecast(digest.digest(), 'uint8');
    hash_value = upper(reshape(dec2hex(raw, 2).', 1, []));
    clear cleanup;
end


function write_json_utf8(path_value, value)
    write_text_utf8(path_value, jsonencode(value, 'PrettyPrint', true));
end


function write_text_utf8(path_value, text_value)
    file_id = fopen(path_value, 'w', 'n', 'UTF-8');
    assert(file_id >= 0, 'Board20Step8ERepeatability:TextOpenFailed', ...
        '无法写入文本：%s', path_value);
    cleanup = onCleanup(@() fclose(file_id));
    count = fwrite(file_id, text_value, 'char');
    assert(count == strlength(string(text_value)), ...
        'Board20Step8ERepeatability:TextWriteFailed', ...
        '文本未完整写入：%s', path_value);
    clear cleanup;
end
