function evidence = verify_board20_step8d_matlab_repeatability()
%VERIFY_BOARD20_STEP8D_MATLAB_REPEATABILITY 真实复跑两轮并写机器可读证据。
%
% 本包装器不重建任何矩阵或求解公式。每轮都直接调用当前磁盘上的
% run_board20_step8d_pilot_matlab，再从该轮实际生成的CSV、MAT合同和
% JSON摘要读取哈希与科学统计。两轮摘要副本会保留在MATLAB输出目录。

    wrapper_path = [mfilename('fullpath'), '.m'];
    code_dir = fileparts(wrapper_path);
    board_dir = fileparts(code_dir);
    main_script_path = fullfile(code_dir, ...
        'run_board20_step8d_pilot_matlab.m');
    output_dir = fullfile(board_dir, 'outputs', ...
        'step8d_单点双求解器门禁', 'matlab');
    assert(isfile(main_script_path), ...
        'Board20Step8DRepeatability:MainScriptMissing', ...
        '缺少最终MATLAB主脚本：%s', main_script_path);
    assert(isfolder(output_dir), ...
        'Board20Step8DRepeatability:OutputDirectoryMissing', ...
        '缺少MATLAB输出目录：%s', output_dir);

    evidence_csv = fullfile(output_dir, 'MATLAB两轮确定性证据.csv');
    evidence_json = fullfile(output_dir, 'MATLAB两轮确定性证据.json');
    run1_summary_copy = fullfile(output_dir, ...
        'MATLAB确定性_第一轮科学摘要.json');
    run2_summary_copy = fullfile(output_dir, ...
        'MATLAB确定性_第二轮科学摘要.json');
    exact_outputs = {evidence_csv, evidence_json, ...
        run1_summary_copy, run2_summary_copy};
    for output_index = 1:numel(exact_outputs)
        if isfile(exact_outputs{output_index})
            delete(exact_outputs{output_index});
        end
    end

    command_text = [ ...
        'matlab -batch "cd(''', normalize_path(code_dir), ...
        '''); evidence=verify_board20_step8d_matlab_repeatability();"'];
    wrapper_sha256 = file_sha256(wrapper_path);

    main_sha_before_run1 = file_sha256(main_script_path);
    summary1 = run_board20_step8d_pilot_matlab();
    main_sha_after_run1 = file_sha256(main_script_path);
    assert(strcmp(main_sha_before_run1, main_sha_after_run1), ...
        'Board20Step8DRepeatability:MainScriptChangedDuringRun1', ...
        '第一轮执行期间最终MATLAB主脚本SHA发生变化。');
    run1 = capture_actual_run(summary1, 1, main_sha_after_run1);
    copy_summary(summary1.output_files.summary, run1_summary_copy);
    run1.saved_summary_copy = run1_summary_copy;
    run1.saved_summary_copy_sha256 = file_sha256(run1_summary_copy);

    main_sha_before_run2 = file_sha256(main_script_path);
    assert(strcmp(main_sha_after_run1, main_sha_before_run2), ...
        'Board20Step8DRepeatability:MainScriptChangedBetweenRuns', ...
        '两轮之间最终MATLAB主脚本SHA发生变化。');
    summary2 = run_board20_step8d_pilot_matlab();
    main_sha_after_run2 = file_sha256(main_script_path);
    assert(strcmp(main_sha_before_run2, main_sha_after_run2), ...
        'Board20Step8DRepeatability:MainScriptChangedDuringRun2', ...
        '第二轮执行期间最终MATLAB主脚本SHA发生变化。');
    run2 = capture_actual_run(summary2, 2, main_sha_after_run2);
    copy_summary(summary2.output_files.summary, run2_summary_copy);
    run2.saved_summary_copy = run2_summary_copy;
    run2.saved_summary_copy_sha256 = file_sha256(run2_summary_copy);

    checks = struct( ...
        'main_script_sha256_equal', ...
            strcmp(run1.main_script_sha256, run2.main_script_sha256), ...
        'point_csv_sha256_equal', ...
            strcmp(run1.point_csv_sha256, run2.point_csv_sha256), ...
        'normalized_scientific_array_sha256_equal', ...
            strcmp(run1.normalized_scientific_array_sha256, ...
                run2.normalized_scientific_array_sha256), ...
        'both_have_312_records', ...
            run1.actual_result_count == 312 && run2.actual_result_count == 312, ...
        'both_all_points_pass', ...
            run1.all_points_pass && run2.all_points_pass && ...
            run1.summary_fail_point_count == 0 && ...
            run2.summary_fail_point_count == 0, ...
        'both_mat_contracts_match_summaries', ...
            run1.mat_contract_matches_summary && ...
            run2.mat_contract_matches_summary, ...
        'both_point_csvs_match_summary_counts', ...
            run1.point_csv_matches_summary_count && ...
            run2.point_csv_matches_summary_count);
    check_names = fieldnames(checks);
    check_values = cellfun(@(name) logical(checks.(name)), check_names);
    overall_pass = all(check_values);

    rows = [run_to_table_row(run1); run_to_table_row(run2)];
    writetable(struct2table(rows), evidence_csv, 'Encoding', 'UTF-8');
    evidence = struct( ...
        'schema', 'board20-step8d-matlab-repeatability-evidence-v1', ...
        'execution_command', command_text, ...
        'main_script_path', main_script_path, ...
        'wrapper_path', wrapper_path, ...
        'wrapper_sha256', wrapper_sha256, ...
        'hash_source_policy', ...
            ['point_csv_sha256=file bytes after each actual run; ' ...
             'normalized_scientific_array_sha256=' ...
             'solver_contract.scientific_array_sha256 loaded from each run MAT'], ...
        'run1', run1, ...
        'run2', run2, ...
        'checks', checks, ...
        'overall_pass', overall_pass, ...
        'evidence_csv', evidence_csv, ...
        'run1_summary_copy', run1_summary_copy, ...
        'run2_summary_copy', run2_summary_copy);
    write_json_utf8(evidence_json, evidence);

    fprintf(['步骤8D MATLAB两轮确定性：overall=%d，CSV_SHA相同=%d，' ...
        '科学数组SHA相同=%d。\n'], overall_pass, ...
        checks.point_csv_sha256_equal, ...
        checks.normalized_scientific_array_sha256_equal);
    if ~overall_pass
        error('Board20Step8DRepeatability:FinalGateFailed', ...
            'MATLAB两轮确定性证据已保存，但至少一个固定门未通过。');
    end
end


function run = capture_actual_run(summary, run_index, main_script_sha256)
    result_csv_path = summary.output_files.results;
    arrays_path = summary.output_files.arrays;
    summary_path = summary.output_files.summary;
    assert(isfile(result_csv_path) && isfile(arrays_path) && ...
        isfile(summary_path), ...
        'Board20Step8DRepeatability:RunOutputMissing', ...
        '第%d轮缺少CSV、MAT或JSON主输出。', run_index);
    loaded = load(arrays_path, 'scientific_records', 'solver_contract');
    assert(isfield(loaded, 'scientific_records') && ...
        isfield(loaded, 'solver_contract'), ...
        'Board20Step8DRepeatability:MatContractMissing', ...
        '第%d轮MAT缺少scientific_records或solver_contract。', run_index);
    scientific_sha = char(loaded.solver_contract.scientific_array_sha256);
    summary_scientific_sha = char(summary.scientific_array_sha256);
    csv_table = readtable(result_csv_path, 'TextType', 'string', ...
        'VariableNamingRule', 'preserve');
    pass_count = nnz(csv_table.point_status == "PASS");
    fail_count = nnz(csv_table.point_status == "FAIL");

    run = struct( ...
        'run_index', run_index, ...
        'main_script_sha256', main_script_sha256, ...
        'point_csv_path', result_csv_path, ...
        'point_csv_sha256', file_sha256(result_csv_path), ...
        'mat_path', arrays_path, ...
        'mat_container_sha256', file_sha256(arrays_path), ...
        'normalized_scientific_array_sha256', scientific_sha, ...
        'summary_reported_scientific_array_sha256', ...
            summary_scientific_sha, ...
        'mat_contract_matches_summary', ...
            strcmp(scientific_sha, summary_scientific_sha), ...
        'summary_path', summary_path, ...
        'summary_sha256_at_capture', file_sha256(summary_path), ...
        'actual_result_count', height(csv_table), ...
        'point_csv_pass_count', pass_count, ...
        'point_csv_fail_count', fail_count, ...
        'point_csv_matches_summary_count', ...
            height(csv_table) == summary.actual_result_count && ...
            pass_count == summary.pass_point_count && ...
            fail_count == summary.fail_point_count, ...
        'summary_pass_point_count', summary.pass_point_count, ...
        'summary_fail_point_count', summary.fail_point_count, ...
        'stable_point_count', summary.stable_point_count, ...
        'critical_point_count', summary.critical_point_count, ...
        'unstable_point_count', summary.unstable_point_count, ...
        'maximum_state_matrix_relative_residual', ...
            summary.maximum_pass_state_matrix_relative_residual, ...
        'maximum_polynomial_relative_residual', ...
            summary.maximum_pass_polynomial_relative_residual, ...
        'minimum_physical_root_magnitude', ...
            summary.minimum_physical_root_magnitude, ...
        'minimum_minimal_augmented_order', ...
            summary.minimum_minimal_augmented_order, ...
        'maximum_minimal_augmented_order', ...
            summary.maximum_minimal_augmented_order, ...
        'minimum_delay_line_gamma', summary.minimum_delay_line_gamma, ...
        'maximum_delay_line_gamma', summary.maximum_delay_line_gamma, ...
        'solver_elapsed_seconds', summary.solver_elapsed_seconds, ...
        'all_points_pass', logical(summary.all_points_pass), ...
        'saved_summary_copy', '', ...
        'saved_summary_copy_sha256', '');
    assert(numel(loaded.scientific_records) == height(csv_table), ...
        'Board20Step8DRepeatability:MatCsvCountMismatch', ...
        '第%d轮MAT科学记录数与CSV行数不符。', run_index);
end


function row = run_to_table_row(run)
    row = struct( ...
        'run_index', run.run_index, ...
        'main_script_sha256', run.main_script_sha256, ...
        'point_csv_sha256', run.point_csv_sha256, ...
        'normalized_scientific_array_sha256', ...
            run.normalized_scientific_array_sha256, ...
        'mat_container_sha256', run.mat_container_sha256, ...
        'summary_sha256_at_capture', run.summary_sha256_at_capture, ...
        'saved_summary_copy_sha256', run.saved_summary_copy_sha256, ...
        'actual_result_count', run.actual_result_count, ...
        'point_csv_pass_count', run.point_csv_pass_count, ...
        'point_csv_fail_count', run.point_csv_fail_count, ...
        'stable_point_count', run.stable_point_count, ...
        'critical_point_count', run.critical_point_count, ...
        'unstable_point_count', run.unstable_point_count, ...
        'maximum_state_matrix_relative_residual', ...
            run.maximum_state_matrix_relative_residual, ...
        'maximum_polynomial_relative_residual', ...
            run.maximum_polynomial_relative_residual, ...
        'minimum_physical_root_magnitude', ...
            run.minimum_physical_root_magnitude, ...
        'minimum_minimal_augmented_order', ...
            run.minimum_minimal_augmented_order, ...
        'maximum_minimal_augmented_order', ...
            run.maximum_minimal_augmented_order, ...
        'minimum_delay_line_gamma', run.minimum_delay_line_gamma, ...
        'maximum_delay_line_gamma', run.maximum_delay_line_gamma, ...
        'solver_elapsed_seconds', run.solver_elapsed_seconds, ...
        'mat_contract_matches_summary', run.mat_contract_matches_summary, ...
        'point_csv_matches_summary_count', ...
            run.point_csv_matches_summary_count, ...
        'all_points_pass', run.all_points_pass, ...
        'saved_summary_copy', run.saved_summary_copy);
end


function copy_summary(source_path, destination_path)
    [copied, message] = copyfile(source_path, destination_path, 'f');
    assert(copied, 'Board20Step8DRepeatability:SummaryCopyFailed', ...
        '无法保留科学摘要副本：%s', message);
end


function value = normalize_path(path_value)
    value = strrep(path_value, '\', '/');
end


function hash_value = file_sha256(path_value)
    file_id = fopen(path_value, 'rb');
    assert(file_id >= 0, 'Board20Step8DRepeatability:HashOpenFailed', ...
        '无法读取待哈希文件：%s', path_value);
    cleanup = onCleanup(@() fclose(file_id));
    digest = java.security.MessageDigest.getInstance('SHA-256');
    while true
        bytes = fread(file_id, 1024 * 1024, '*uint8');
        if isempty(bytes)
            break;
        end
        digest.update(typecast(bytes(:), 'int8'));
    end
    raw_digest = typecast(digest.digest(), 'uint8');
    hash_value = upper(reshape(dec2hex(raw_digest, 2).', 1, []));
    clear cleanup;
end


function write_json_utf8(path_value, value)
    encoded = jsonencode(value, 'PrettyPrint', true);
    file_id = fopen(path_value, 'w', 'n', 'UTF-8');
    assert(file_id >= 0, 'Board20Step8DRepeatability:JsonOpenFailed', ...
        '无法写入JSON：%s', path_value);
    cleanup = onCleanup(@() fclose(file_id));
    count = fwrite(file_id, encoded, 'char');
    assert(count == strlength(string(encoded)), ...
        'Board20Step8DRepeatability:JsonWriteFailed', ...
        'JSON未完整写入：%s', path_value);
    clear cleanup;
end
