from pathlib import Path
import json,base64,html,shutil
TMP=Path(__file__).resolve().parent;NEW=TMP.parents[1].parent/'260817/elsevier_review_v2_refined_20260907'
if TMP.name=='code' and TMP.parent.name=='refinement_evidence':NEW=TMP.parents[1]
EV=NEW/'refinement_evidence';metric=json.loads((EV/'data/modal_share_deviation.json').read_text('utf-8'));ops=json.loads((EV/'manuscript_changes.json').read_text('utf-8'))
image=lambda name:'data:image/png;base64,'+base64.b64encode((NEW/'submit_figure'/name).read_bytes()).decode()
modelrows=''.join(f'<tr><td>划分{"I"*m["division"]}</td><td>{"Craig–Bampton" if m["method"]=="CB" else m["method"]}</td><td>{m["previous_signed_sum"]:.4f}</td><td><strong>{m["absolute_relative_deviation_sum"]:.4f}</strong></td></tr>'for m in metric['model_totals'])
barrows=''.join(f'<tr><td>划分{"I"*r["division"]}</td><td>{"Craig–Bampton" if r["method"]=="CB" else r["method"]}</td><td>ψ<sub>{r["physical_dof"]}</sub></td><td>{r["absolute_relative_deviation"]:.6f}</td><td>{100*r["absolute_relative_deviation"]:.4f}%</td></tr>' for r in metric['per_coordinate'])
changes=''.join(f'<details><summary>{i}. {html.escape(o["reason"])}</summary><div class="comparison"><div><b>上一版</b><pre>{html.escape(o["old"])}</pre></div><div><b>本版</b><pre>{html.escape(o["new"])}</pre></div></div></details>' for i,o in enumerate(ops,1))
doc=r'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>图6排版与图15变化幅度指标修改汇报</title><style>
*{box-sizing:border-box}body{margin:0;background:#edf2f5;color:#1a3041;font:17px/1.85 "Microsoft YaHei",sans-serif}main{max-width:1100px;margin:auto;padding:45px 55px 70px;background:white}h1{font-size:32px;line-height:1.5;margin:8px 0 18px}h2{font-size:25px;margin:0 0 17px;line-height:1.5}h3{font-size:19px;margin:20px 0 10px}p{margin:10px 0 17px}.eyebrow,.muted,figcaption{color:#536d7e;font-size:14px}.lead{font-size:20px}header{border-bottom:3px solid #20394b;padding-bottom:22px}nav{display:flex;gap:12px 22px;flex-wrap:wrap;margin:22px 0}a{color:#235f8a;text-underline-offset:4px}section{padding:32px 0 12px;border-top:1px solid #d5dfe6;scroll-margin-top:15px}figure{margin:20px 0}img{display:block;width:100%;height:auto}figcaption{margin-top:10px}.formula{font:23px/2.2 "Cambria Math",Cambria,serif;text-align:center;background:#f3f7fa;border:1px solid #d5dfe6;border-radius:9px;padding:17px;margin:18px 0;overflow-x:auto}.frac{display:inline-flex;flex-direction:column;vertical-align:middle;text-align:center;line-height:1.7;margin:0 5px}.frac span:first-child{border-bottom:1px solid}.frac span{padding:0 7px}.callout{padding:17px 23px;background:#eef5fa;border-left:4px solid #4477aa;margin:20px 0}.table-wrap{overflow-x:auto;margin:18px 0}table{width:100%;border-collapse:collapse;font-size:15px;white-space:nowrap;font-variant-numeric:tabular-nums}th,td{padding:10px 12px;border-bottom:1px solid #d5dfe6;text-align:right}th:first-child,td:first-child{text-align:left}thead th{border-top:2px solid #20394b;border-bottom:1px solid #20394b;background:#f6f8fa}tbody tr:nth-child(even){background:#f8fafb}details{border:1px solid #d5dfe6;border-radius:8px;padding:12px 16px;margin:13px 0}summary{cursor:pointer;font-weight:700}.comparison{display:grid;grid-template-columns:1fr 1fr;gap:20px;padding:14px 0 0}.comparison>div{min-width:0}pre{font:12px/1.75 Consolas,"Microsoft YaHei",monospace;white-space:pre-wrap;overflow-wrap:anywhere;background:#f5f7f9;padding:12px;border-radius:5px}button{font:inherit;font-size:14px;border:1px solid #869cab;border-radius:7px;padding:9px 16px;background:white;color:#20394b;cursor:pointer}code{font-size:13px;overflow-wrap:anywhere}.print-note{display:none}
@media(max-width:700px){body{font-size:16px}main{padding:25px 20px 45px}h1{font-size:27px}h2{font-size:23px}.lead{font-size:18px}.comparison{grid-template-columns:1fr}.formula{font-size:18px;padding:12px}.callout{padding:14px 17px}table{font-size:13px}th,td{padding:8px}}
@media print{@page{size:A4;margin:15mm}body{background:white;font-size:10pt;line-height:1.65}main{padding:0;max-width:none}header{padding-bottom:12px}h1{font-size:22pt}h2{font-size:16pt}h3{font-size:12pt}.lead{font-size:12pt}nav,.no-print{display:none}section{break-before:page;border:0;padding:0}h2,h3,summary{break-after:avoid}figure,.formula,.table-wrap,.callout{break-inside:avoid}p{orphans:3;widows:3}.formula{font-size:15pt;padding:12px}.table-wrap{overflow:visible}table{font-size:9pt}th,td{padding:6px 8px}tr{break-inside:avoid}figcaption,.muted,.eyebrow{font-size:8.5pt}details:not([open]){display:none}.comparison{display:block}pre{font-size:8pt}.print-note{display:block}}
</style></head><body><main><header><div class="eyebrow">RHTS · 本轮修改 · 2026-09-07</div><h1>图6频率信息移入子图<br>图15改为评价份额的变化幅度</h1><p class="lead">Doctor Bego，已按您的选择完成两项修改：图6的12项频率以8pt放入相应子图的空白处；图15采用逐坐标绝对相对变化，并同步公式、表5和全文引用。</p><p>新稿共38页。图6位于第24页，图15与表5位于第33页。图13的一行四图保持，位于第31页。上一版全部86个文件保留，本版在独立文件夹交付。</p></header><nav><a href="#figure6">图6新布局</a><a href="#metric">指标怎样改变</a><a href="#figure15">图15新图与柱值</a><a href="#changes">全文同步与验收</a></nav>
<section id="figure6"><h2>图6：所有频率都放回对应子图</h2><figure><img src="@@FIG6@@" alt="图6采用一行四个竖长子图，12项频率以8pt放在图内空白处。第一阶位于左侧，第二阶位于右下方。"><figcaption>第一阶子图(a,c)的负位移区域有连续空白，频率信息放在左侧；第二阶子图(b,d)的右下方为空白，频率信息放在那里。每个子图内均包含Hz单位和完整模型、Guyan、Craig–Bampton的3项频率。</figcaption></figure><p>1行4列、12条振型曲线、方法配色和频率数值全部保持。图内信息使用8pt，曲线周围保留间距；图外下方只保留共用横轴名称。</p><p class="muted">验收：4组注释的包围框均位于坐标轴内，与三条响应曲线无相交；额外扩展2.5pt后仍无相交。已实际查看600dpi PNG及编译后的论文页面。</p></section>
<section id="metric"><h2>关注变化程度，就将每个坐标的偏离幅度计入指标</h2><p>正负号用于区分增加和减少。您现在关注的是缩聚后的份额偏离完整模型多远，因此指标改为<strong>每一项先取绝对值，再相加</strong>。方向仍可从图15左侧的份额曲线看出，右侧集中展示偏离程度。</p><div class="formula">ΔE = Σ<sub>k=1…nₐ</sub> <span style="font-size:1.6em;vertical-align:middle">|</span><span class="frac"><span>E<sup>red</sup>(d<sub>k</sub>) − E<sup>full</sup>(d<sub>k</sub>)</span><span>E<sup>full</sup>(d<sub>k</sub>)</span></span><span style="font-size:1.6em;vertical-align:middle">|</span></div><p>其中，E是该坐标的模态份额，red与full分别表示缩聚模型和完整模型，d<sub>k</sub>是第k个作动坐标。本算例两种划分都取两个作动坐标相加；值越小，所选坐标的模态份额越接近完整模型。正文统一称为<strong>modal-share deviation（模态份额偏离程度）</strong>。</p><div class="callout">划分II的Guyan：首层偏离幅度1.138673，顶层偏离幅度0.247253，相加得到<strong>1.385926</strong>，表5显示为<strong>1.3859</strong>。取绝对值发生在每个坐标内部，不是对原来的0.8914整体取绝对值。</div><div class="table-wrap"><table id="model-totals"><thead><tr><th>结构划分</th><th>方法</th><th>上一版指标</th><th>本版变化幅度</th></tr></thead><tbody>@@MODELS@@</tbody></table></div><p>模态本身、参与权重和左图的90个份额数值都保持。本次改变的是如何把这些份额与参考模型的差异汇总成指标，未重新调整结构或响应数据。</p></section>
<section id="figure15"><h2>图15：左侧保留份额，右侧展示偏离幅度</h2><figure><img src="@@FIG15@@" alt="更新后的图15：左侧两幅模态份额曲线保持；右侧所有柱子均为各作动坐标绝对相对变化。"><figcaption>上排是划分I，作动坐标为首层ψ₁和中层ψ₆；下排是划分II，作动坐标为首层ψ₁和顶层ψ₁₁。右图柱高越小，表示对应坐标的份额越接近完整模型。上下排右图的纵轴尺度不同，应按刻度读数。</figcaption></figure><div class="table-wrap"><table id="bar-values"><thead><tr><th>结构划分</th><th>方法</th><th>作动坐标</th><th>右图柱高</th><th>相对偏离幅度</th></tr></thead><tbody>@@BARS@@</tbody></table></div><p>Craig–Bampton在两种划分下的柱值和相加值均较小，说明它更好地保留了所选作动坐标的低阶模态份额。图15用于这一模态分布比较；延迟稳定性由含控制器和延迟通道的闭环模型判断。</p></section>
<section id="changes"><h2>公式、表格、图注和正文已按同一定义同步</h2><p>本轮共16处局部修改，覆盖图6图注、引言中的指标说明、式(4.4)、指标解释、结果章节标题、表5、图15图注与讨论、结论中的四个数值。新增变化保持红色，原42条负间距命令不变。</p><p>两个独立数值路径对图15全部8个柱值交叉核对，最大差1.37×10<sup>−14</sup>；图6曲线和12项频率与上一版完全一致。主稿执行pdfLaTeX→BibTeX→pdfLaTeX两遍，41项编译与一致性检查通过，无Error、未定义引用/文献或“??”。</p><p class="muted">按此前要求保留负间距，原第6、7、8、12、13、21、22页的部分公式紧贴/重叠仍保留。本轮没有扩大结构模型或闭环稳定性计算范围。此前版图13/15讲解报告保留为历史版本；本版图15按这里的变化幅度定义阅读。</p><button type="button" class="no-print" id="expand-all">展开全部原文对照</button><p class="print-note">逐项完整原文对照保留在HTML中；展开后可一并打印。</p>@@CHANGES@@<h3>文件入口与当前状态</h3><p><code>main.tex</code>是可编辑主稿；<code>main.pdf</code>是38页编译稿；<code>submit_figure</code>保存投稿图；<code>refinement_evidence/data/modal_share_deviation.json</code>保存新指标及逐坐标值，<code>manuscript_changes.json</code>与<code>main_changes.diff</code>保存完整变更。本轮修改已完成，待您审阅。</p></section>
</main><script>document.getElementById('expand-all').addEventListener('click',function(){const open=!document.querySelector('details').open;document.querySelectorAll('details').forEach(x=>x.open=open);this.textContent=open?'收起全部原文对照':'展开全部原文对照'})</script></body></html>'''
doc=doc.replace('三条响应曲线','三条振型曲线')
doc=doc.replace('Craig–Bampton在两种划分下的柱值和相加值均较小，说明它更好地保留了所选作动坐标的低阶模态份额。','Craig–Bampton在两种划分下的合计偏离均较小，说明它整体上更好地保留了所选作动坐标的低阶模态份额。划分I中层的单项偏离略大（0.002502对0.002017），其余三个坐标比较均较小。')
for key,value in {'FIG6':image('fig12_horizontal_modes.png'),'FIG15':image('fig16_modal_shares.png'),'MODELS':modelrows,'BARS':barrows,'CHANGES':changes}.items():doc=doc.replace('@@'+key+'@@',value)
assert '@@' not in doc
(NEW/'图6排版与图15变化幅度指标修改汇报.html').write_text(doc,encoding='utf-8')
if Path(__file__).resolve()!=(EV/'code/build_report.py').resolve():shutil.copy2(__file__,EV/'code/build_report.py')
print('Report created; numeric rows: 4 model totals, 8 coordinate deviations; 16 exact changes.')
