function summary = run_board20_step8d_pilot_matlab()
%RUN_BOARD20_STEP8D_PILOT_MATLAB 步骤8D：24个论文候选的冻结单点门禁。
%
% 本函数只读取步骤8C/Python生成的36个候选数值包，只允许R01--R04
% 且paper_grid_eligible_code=1的24个包进入求根；R05/R06的12个诊断包
% 必须被明确拒绝。函数不读取论文PDF、历史稳定域掩膜或历史曲线数值。
%
% 每个冻结点先验证两通道共享左向量和秩一时滞力合同，再解析构造
% 2n+l+j阶标量延迟线最小增广。全部最小增广根均为物理根，不执行幅值
% 过滤。每个特征对同时通过状态矩阵和原清幂矩阵多项式的1e-8回代门。
% 已证伪的n(max(l,j)+2)阶大伴随根排序不进入本主输出或谱半径判定。

    code_path = [mfilename('fullpath'), '.m'];
    code_dir = fileparts(code_path);
    board_dir = fileparts(code_dir);
    input_dir = fullfile(board_dir, 'outputs', ...
        'step8c_六链模型生成', 'python', '候选数值包');
    output_dir = fullfile(board_dir, 'outputs', ...
        'step8d_单点双求解器门禁', 'matlab');

    assert(isfolder(input_dir), 'Board20Step8D:InputDirectoryMissing', ...
        '步骤8C候选包目录不存在：%s', input_dir);
    if ~isfolder(output_dir)
        [made, message] = mkdir(output_dir);
        assert(made, 'Board20Step8D:OutputDirectoryCreateFailed', ...
            '无法创建输出目录%s：%s', output_dir, message);
    end

    output_paths = struct( ...
        'points', fullfile(output_dir, '冻结试点清单.csv'), ...
        'admission', fullfile(output_dir, '36候选准入门禁.csv'), ...
        'results', fullfile(output_dir, 'MATLAB试点逐点结果.csv'), ...
        'arrays', fullfile(output_dir, 'MATLAB试点原始科学数组.mat'), ...
        'summary', fullfile(output_dir, 'MATLAB步骤8D摘要.json'));
    output_fields = fieldnames(output_paths);
    for k = 1:numel(output_fields)
        delete_exact_file_if_present(output_paths.(output_fields{k}));
    end

    % 冻结点清单必须先写盘；此后任何数值结果都不得改变该清单。
    point_id = ["P00"; "P01"; "P02"; "P03"; "P04"; "P05"; "P06"; ...
        "P07"; "P08"; "P09"; "P10"; "P11"; "P12"];
    l_delay = [0; 1; 0; 3; 10; 15; 30; 1; 1; 1; 1; 1; 1];
    j_delay = [0; 0; 1; 7; 20; 33; 66; 48; 51; 57; 58; 59; 64];
    point_purpose = [repmat("固定通用验收点", 7, 1); ...
        repmat("论文六条右端列附近低行验收点", 6, 1)];
    points_table = table(point_id, l_delay, j_delay, point_purpose);
    writetable(points_table, output_paths.points, 'Encoding', 'UTF-8');
    frozen_point_signature = point_signature(points_table);

    files = dir(fullfile(input_dir, '*.mat'));
    assert(numel(files) == 36, 'Board20Step8D:BundleCountMismatch', ...
        '步骤8C候选包必须恰有36个，实际为%d个。', numel(files));
    [~, file_order] = sort({files.name});
    files = files(file_order);

    admission = repmat(empty_admission_record(), numel(files), 1);
    eligible_packages = repmat(empty_package_record(), 0, 1);
    for file_index = 1:numel(files)
        bundle_path = fullfile(files(file_index).folder, files(file_index).name);
        bundle = load(bundle_path);
        assert_bundle_contract(bundle, bundle_path);

        division = exact_integer_scalar(bundle.division, 'division', bundle_path);
        method_index = exact_integer_scalar(bundle.method_index, ...
            'method_index', bundle_path);
        candidate_index = exact_integer_scalar(bundle.candidate_index, ...
            'candidate_index', bundle_path);
        dimension = exact_integer_scalar(bundle.route_dimension, ...
            'route_dimension', bundle_path);
        formula_valid = exact_binary_scalar(bundle.formula_valid_code, ...
            'formula_valid_code', bundle_path);
        paper_eligible = exact_binary_scalar(bundle.paper_grid_eligible_code, ...
            'paper_grid_eligible_code', bundle_path);

        assert(any(division == [1, 2]), 'Board20Step8D:InvalidDivision', ...
            'division不是1或2：%s', bundle_path);
        assert(any(method_index == [1, 2, 3]), ...
            'Board20Step8D:InvalidMethodIndex', ...
            'method_index不是1、2或3：%s', bundle_path);
        assert(any(candidate_index == 1:6), ...
            'Board20Step8D:InvalidCandidateIndex', ...
            'candidate_index不在1--6：%s', bundle_path);

        expected_eligible = candidate_index <= 4;
        if expected_eligible
            assert(formula_valid == 1 && paper_eligible == 1, ...
                'Board20Step8D:EligibleCodeMismatch', ...
                'R01--R04必须同时满足formula_valid_code=1和paper_grid_eligible_code=1：%s', ...
                bundle_path);
            admission_status = 'ACCEPTED_PAPER_GRID';
            rejection_reason = '';
            package = empty_package_record();
            package.bundle_path = bundle_path;
            package.bundle = bundle;
            package.division = division;
            package.method_index = method_index;
            package.candidate_index = candidate_index;
            package.dimension = dimension;
            eligible_packages(end + 1) = package; %#ok<AGROW>
        else
            assert(any(candidate_index == [5, 6]), ...
                'Board20Step8D:UnexpectedRejectedCandidate', ...
                '被拒候选必须且只能是R05/R06：%s', bundle_path);
            assert(formula_valid == 0 && paper_eligible == 0, ...
                'Board20Step8D:DiagnosticCodeMismatch', ...
                'R05/R06必须同时满足formula_valid_code=0和paper_grid_eligible_code=0：%s', ...
                bundle_path);
            admission_status = 'REJECTED_DIAGNOSTIC_ONLY';
            rejection_reason = ...
                'R05/R06_HISTORICAL_DIAGNOSTIC_NOT_FORMULA_VALID';
        end

        admission(file_index) = struct( ...
            'bundle_id', make_bundle_id(division, method_index, candidate_index), ...
            'division', division, ...
            'method_index', method_index, ...
            'method_name', method_name(method_index), ...
            'candidate_id', sprintf('R%02d', candidate_index), ...
            'route_dimension', dimension, ...
            'formula_valid_code', formula_valid, ...
            'paper_grid_eligible_code', paper_eligible, ...
            'admission_status', admission_status, ...
            'rejection_reason', rejection_reason, ...
            'bundle_path', bundle_path);
    end

    assert(numel(eligible_packages) == 24, ...
        'Board20Step8D:EligibleCountMismatch', ...
        '必须恰有24个R01--R04论文候选被准入，实际为%d个。', ...
        numel(eligible_packages));
    assert(nnz(strcmp({admission.admission_status}, ...
        'REJECTED_DIAGNOSTIC_ONLY')) == 12, ...
        'Board20Step8D:RejectedCountMismatch', ...
        '必须显式拒绝12个R05/R06诊断包。');
    for candidate_index = 1:6
        assert(nnz(strcmp({admission.candidate_id}, ...
            sprintf('R%02d', candidate_index))) == 6, ...
            'Board20Step8D:CandidateMultiplicityMismatch', ...
            '每个候选必须覆盖六条路线；R%02d未满足。', candidate_index);
    end
    writetable(struct2table(admission), output_paths.admission, ...
        'Encoding', 'UTF-8');

    % 固定求解顺序，保证失败可定位并便于跨语言逐点对齐。
    package_keys = [[eligible_packages.division].', ...
        [eligible_packages.method_index].', ...
        [eligible_packages.candidate_index].'];
    [~, package_order] = sortrows(package_keys, [1, 2, 3]);
    eligible_packages = eligible_packages(package_order);

    expected_result_count = numel(eligible_packages) * height(points_table);
    result_records = repmat(empty_result_record(), expected_result_count, 1);
    scientific_records = repmat(empty_scientific_record(), ...
        expected_result_count, 1);
    record_index = 0;
    solver_start = tic;

    for package_index = 1:numel(eligible_packages)
        package = eligible_packages(package_index);
        bundle_id = make_bundle_id(package.division, package.method_index, ...
            package.candidate_index);
        fprintf('步骤8D MATLAB：%s（%d/%d）\n', bundle_id, ...
            package_index, numel(eligible_packages));
        for point_index = 1:height(points_table)
            record_index = record_index + 1;
            current_point_id = char(points_table.point_id(point_index));
            current_l = points_table.l_delay(point_index);
            current_j = points_table.j_delay(point_index);
            point_result = solve_minimal_augmented_point( ...
                package.bundle, current_l, current_j);

            result_records(record_index) = struct( ...
                'bundle_id', bundle_id, ...
                'division', package.division, ...
                'method_index', package.method_index, ...
                'method_name', method_name(package.method_index), ...
                'candidate_id', sprintf('R%02d', package.candidate_index), ...
                'route_dimension', package.dimension, ...
                'point_id', current_point_id, ...
                'l_delay', current_l, ...
                'j_delay', current_j, ...
                'rho', point_result.rho, ...
                'expected_physical_root_count', ...
                    point_result.expected_physical_root_count, ...
                'physical_root_count', numel(point_result.physical_roots), ...
                'minimum_physical_root_magnitude', ...
                    point_result.minimum_physical_root_magnitude, ...
                'shared_left_max_relative_error', ...
                    point_result.shared_left_max_relative_error, ...
                'rank_one_force_max_relative_error', ...
                    point_result.rank_one_force_max_relative_error, ...
                'delay_line_gamma_1', point_result.delay_line_gamma(1), ...
                'delay_line_gamma_2', point_result.delay_line_gamma(2), ...
                'polynomial_degree', point_result.polynomial_degree, ...
                'clearing_power', point_result.clearing_power, ...
                'minimal_augmented_order', ...
                    point_result.minimal_augmented_order, ...
                'max_state_matrix_relative_residual', ...
                    point_result.max_state_matrix_relative_residual, ...
                'max_polynomial_relative_residual', ...
                    point_result.max_polynomial_relative_residual, ...
                'point_status', point_result.point_status, ...
                'stability_class', point_result.stability_class, ...
                'failure_identifier', point_result.failure_identifier, ...
                'failure_message', point_result.failure_message);

            scientific_records(record_index) = struct( ...
                'bundle_id', bundle_id, ...
                'division', package.division, ...
                'method_index', package.method_index, ...
                'candidate_index', package.candidate_index, ...
                'route_dimension', package.dimension, ...
                'point_id', current_point_id, ...
                'l_delay', current_l, ...
                'j_delay', current_j, ...
                'laurent_exponents', point_result.laurent_exponents, ...
                'laurent_coefficient_frobenius_norms', ...
                    point_result.laurent_coefficient_frobenius_norms, ...
                'polynomial_degree', point_result.polynomial_degree, ...
                'clearing_power', point_result.clearing_power, ...
                'expected_physical_root_count', ...
                    point_result.expected_physical_root_count, ...
                'minimal_augmented_order', ...
                    point_result.minimal_augmented_order, ...
                'shared_left_channel_relative_errors', ...
                    point_result.shared_left_channel_relative_errors, ...
                'rank_one_force_channel_relative_errors', ...
                    point_result.rank_one_force_channel_relative_errors, ...
                'delay_line_gamma', point_result.delay_line_gamma, ...
                'physical_roots', point_result.physical_roots, ...
                'minimum_physical_root_magnitude', ...
                    point_result.minimum_physical_root_magnitude, ...
                'state_matrix_relative_residuals', ...
                    point_result.state_matrix_relative_residuals, ...
                'physical_root_relative_residuals', ...
                    point_result.physical_root_relative_residuals, ...
                'rho', point_result.rho, ...
                'max_state_matrix_relative_residual', ...
                    point_result.max_state_matrix_relative_residual, ...
                'max_polynomial_relative_residual', ...
                    point_result.max_polynomial_relative_residual, ...
                'point_status', point_result.point_status, ...
                'stability_class', point_result.stability_class, ...
                'failure_identifier', point_result.failure_identifier, ...
                'failure_message', point_result.failure_message);
        end
    end
    solver_elapsed_seconds = toc(solver_start);

    assert(record_index == expected_result_count, ...
        'Board20Step8D:ResultCountMismatch', ...
        '逐点记录数不等于24x13=%d。', expected_result_count);
    assert(strcmp(frozen_point_signature, point_signature(points_table)), ...
        'Board20Step8D:FrozenPointMutation', ...
        '求解期间冻结点清单发生改变。');

    result_table = struct2table(result_records);
    writetable(result_table, output_paths.results, 'Encoding', 'UTF-8');
    scientific_array_sha256 = ...
        scientific_records_sha256(scientific_records);
    solver_contract = struct( ...
        'solver', 'analytic_scalar_delay_line_minimal_augmentation', ...
        'physical_order_policy', 'exactly_2*n+l+j', ...
        'retired_solver_policy', ...
            ['full_n_times_max_delay_plus_2_companion_is_failure_' ...
             'diagnostic_only_and_not_used_in_main_output'], ...
        'scientific_array_sha256', scientific_array_sha256, ...
        'state_matrix_relative_residual_gate', 1e-8, ...
        'polynomial_relative_residual_gate', 1e-8, ...
        'input_policy', ...
            'ONLY_STEP8C_PYTHON_BUNDLES_NO_PDF_NO_HISTORY_MASK', ...
        'frozen_point_signature', frozen_point_signature);
    save(output_paths.arrays, 'scientific_records', 'solver_contract', ...
        'points_table', 'admission', '-v7.3');

    pass_mask = strcmp({result_records.point_status}, 'PASS');
    max_pass_state_residual = NaN;
    max_pass_polynomial_residual = NaN;
    if any(pass_mask)
        max_pass_state_residual = max( ...
            [result_records(pass_mask).max_state_matrix_relative_residual]);
        max_pass_polynomial_residual = max( ...
            [result_records(pass_mask).max_polynomial_relative_residual]);
    end
    summary = struct( ...
        'schema', 'board20-step8d-matlab-pilot-v1', ...
        'input_policy', ...
            'ONLY_STEP8C_PYTHON_BUNDLES_NO_PDF_NO_HISTORY_MASK', ...
        'linearization', 'analytic_scalar_delay_line_minimal_augmentation', ...
        'physical_order_policy', 'exactly_2*n+l+j', ...
        'state_matrix_relative_residual_gate', 1e-8, ...
        'polynomial_relative_residual_gate', 1e-8, ...
        'frozen_point_signature', frozen_point_signature, ...
        'frozen_point_count', height(points_table), ...
        'scanned_bundle_count', numel(files), ...
        'eligible_bundle_count', numel(eligible_packages), ...
        'rejected_R05_R06_bundle_count', 12, ...
        'expected_result_count', expected_result_count, ...
        'actual_result_count', record_index, ...
        'pass_point_count', nnz(pass_mask), ...
        'fail_point_count', nnz(~pass_mask), ...
        'stable_point_count', nnz(strcmp({result_records.stability_class}, ...
            'STABLE')), ...
        'critical_point_count', nnz(strcmp({result_records.stability_class}, ...
            'CRITICAL')), ...
        'unstable_point_count', nnz(strcmp({result_records.stability_class}, ...
            'UNSTABLE')), ...
        'maximum_pass_state_matrix_relative_residual', ...
            max_pass_state_residual, ...
        'maximum_pass_polynomial_relative_residual', ...
            max_pass_polynomial_residual, ...
        'minimum_physical_root_magnitude', ...
            min([result_records.minimum_physical_root_magnitude]), ...
        'minimum_minimal_augmented_order', ...
            min([result_records.minimal_augmented_order]), ...
        'maximum_minimal_augmented_order', ...
            max([result_records.minimal_augmented_order]), ...
        'maximum_shared_left_relative_error', ...
            max([result_records.shared_left_max_relative_error]), ...
        'maximum_rank_one_force_relative_error', ...
            max([result_records.rank_one_force_max_relative_error]), ...
        'minimum_delay_line_gamma', min([ ...
            result_records.delay_line_gamma_1, ...
            result_records.delay_line_gamma_2]), ...
        'maximum_delay_line_gamma', max([ ...
            result_records.delay_line_gamma_1, ...
            result_records.delay_line_gamma_2]), ...
        'scientific_array_sha256', scientific_array_sha256, ...
        'solver_elapsed_seconds', solver_elapsed_seconds, ...
        'all_points_pass', all(pass_mask), ...
        'output_files', output_paths);
    write_json_utf8(output_paths.summary, summary);

    fprintf(['步骤8D MATLAB完成：准入24包，拒绝12包，冻结点13个，' ...
         'PASS=%d，FAIL=%d，最大状态矩阵残差=%.3e，' ...
         '最大多项式残差=%.3e，用时=%.1fs。\n'], ...
        summary.pass_point_count, summary.fail_point_count, ...
        summary.maximum_pass_state_matrix_relative_residual, ...
        summary.maximum_pass_polynomial_relative_residual, ...
        solver_elapsed_seconds);
    if ~summary.all_points_pass
        error('Board20Step8D:FinalPointGateFailed', ...
            ['步骤8D MATLAB已保留全部CSV/MAT/JSON诊断输出，但%d个冻结点' ...
             '未通过固定1e-8回代残差及有限谱半径终态门。'], ...
            summary.fail_point_count);
    end
end


function result = solve_minimal_augmented_point(bundle, l_delay, j_delay)
    result = empty_point_result();
    try
        validate_delay(l_delay, 'l_delay');
        validate_delay(j_delay, 'j_delay');
        n = exact_integer_scalar(bundle.route_dimension, ...
            'route_dimension', 'in-memory bundle');
        dt = finite_positive_scalar(bundle.dt, 'dt');
        mass_operator = finite_square_matrix( ...
            bundle.integration_mass_operator, n, ...
            'integration_mass_operator');
        c1 = finite_square_matrix(bundle.C1, n, 'C1');
        k1 = finite_square_matrix(bundle.K1, n, 'K1');
        feedback_c = finite_square_matrix( ...
            bundle.feedback_C, n, 'feedback_C');
        feedback_k = finite_square_matrix( ...
            bundle.feedback_K, n, 'feedback_K');
        c_left = finite_factor(bundle.active_delay_C_left_factor, n, 2, ...
            'active_delay_C_left_factor');
        c_right = finite_factor(bundle.active_delay_C_right_factor, 2, n, ...
            'active_delay_C_right_factor');
        k_left = finite_factor(bundle.active_delay_K_left_factor, n, 2, ...
            'active_delay_K_left_factor');
        k_right = finite_factor(bundle.active_delay_K_right_factor, 2, n, ...
            'active_delay_K_right_factor');

        delays = [double(l_delay), double(j_delay)];
        expected_order = 2 * n + sum(delays);
        result.expected_physical_root_count = expected_order;
        result.minimal_augmented_order = expected_order;

        shared_errors = zeros(1, 2);
        rank_one_errors = zeros(1, 2);
        for channel = 1:2
            shared_errors(channel) = relative_vector_error( ...
                c_left(:, channel), k_left(:, channel));
            if shared_errors(channel) > 1e-12
                error('Board20Step8D:SharedLeftVectorGateFailed', ...
                    ['通道%d的阻尼/刚度时滞左向量相对误差%.17g' ...
                     '超过固定门1e-12。'], channel, shared_errors(channel));
            end
            shared_left = c_left(:, channel);
            if norm(shared_left, 2) == 0
                error('Board20Step8D:ZeroSharedLeftVector', ...
                    '通道%d的共享时滞力左向量为零。', channel);
            end
            force_pair = [ ...
                shared_left * c_right(channel, :), ...
                shared_left * k_right(channel, :)];
            singular_values = svd(force_pair, 'econ');
            if isempty(singular_values) || singular_values(1) == 0
                rank_one_errors(channel) = Inf;
            elseif isscalar(singular_values)
                rank_one_errors(channel) = 0;
            else
                rank_one_errors(channel) = ...
                    singular_values(2) / singular_values(1);
            end
            if ~(isfinite(rank_one_errors(channel)) && ...
                    rank_one_errors(channel) <= 1e-12)
                error('Board20Step8D:RankOneDelayForceGateFailed', ...
                    ['通道%d的阻尼/刚度联合时滞力秩一相对误差%.17g' ...
                     '超过固定门1e-12。'], ...
                    channel, rank_one_errors(channel));
            end
        end
        result.shared_left_channel_relative_errors = shared_errors;
        result.shared_left_max_relative_error = max(shared_errors);
        result.rank_one_force_channel_relative_errors = rank_one_errors;
        result.rank_one_force_max_relative_error = max(rank_one_errors);

        % 原Laurent方程系数只用于独立的清幂矩阵多项式回代门。
        min_requested_exponent = -(max(delays) + 1);
        exponents = min_requested_exponent:1;
        coefficients = repmat({zeros(n)}, 1, numel(exponents));
        inertial = mass_operator / (dt ^ 2);
        b0 = -2 * inertial + c1 / dt + k1 + ...
            feedback_c / dt + feedback_k;
        b1 = inertial - c1 / dt - feedback_c / dt;
        coefficients = add_coefficient( ...
            coefficients, exponents, 1, inertial);
        coefficients = add_coefficient( ...
            coefficients, exponents, 0, b0);
        coefficients = add_coefficient( ...
            coefficients, exponents, -1, b1);
        for channel = 1:2
            delayed_at_channel = ...
                (c_left(:, channel) * c_right(channel, :)) / dt + ...
                k_left(:, channel) * k_right(channel, :);
            delayed_after_channel = ...
                -(c_left(:, channel) * c_right(channel, :)) / dt;
            coefficients = add_coefficient(coefficients, exponents, ...
                -delays(channel), delayed_at_channel);
            coefficients = add_coefficient(coefficients, exponents, ...
                -(delays(channel) + 1), delayed_after_channel);
        end
        nonzero = cellfun(@has_exact_nonzero, coefficients);
        if ~any(nonzero)
            error('Board20Step8D:IdenticallyZeroPolynomial', ...
                '所有Laurent系数均为零。');
        end
        first = find(nonzero, 1, 'first');
        last = find(nonzero, 1, 'last');
        coefficients = coefficients(first:last);
        exponents = exponents(first:last);
        clearing_power = max(0, -exponents(1));
        shifted_exponents = exponents + clearing_power;
        polynomial = repmat({zeros(n)}, 1, max(shifted_exponents) + 1);
        for coefficient_index = 1:numel(coefficients)
            polynomial{shifted_exponents(coefficient_index) + 1} = ...
                coefficients{coefficient_index};
        end
        while numel(polynomial) > 1 && ...
                ~has_exact_nonzero(polynomial{end})
            polynomial(end) = [];
        end
        degree = numel(polynomial) - 1;
        expected_degree = max(delays) + 2;
        if degree ~= expected_degree
            error('Board20Step8D:PolynomialDegreeMismatch', ...
                '清幂矩阵多项式次数应为%d，实际为%d。', ...
                expected_degree, degree);
        end
        result.laurent_exponents = exponents;
        result.laurent_coefficient_frobenius_norms = ...
            cellfun(@(value) norm(value, 'fro'), coefficients);
        result.polynomial_degree = degree;
        result.clearing_power = clearing_power;

        % 解析的2n+l+j阶标量延迟线最小增广。
        if rcond(inertial) <= eps('double')
            error('Board20Step8D:SingularInertialOperator', ...
                'T=integration_mass_operator/dt^2数值奇异。');
        end
        augmented = zeros(expected_order);
        augmented(1:n, 1:n) = -(inertial \ b0);
        augmented(1:n, n + (1:n)) = -(inertial \ b1);
        augmented(n + (1:n), 1:n) = eye(n);
        next_buffer_index = 2 * n + 1;
        delay_line_gamma = zeros(1, 2);
        for channel = 1:2
            shared_left = c_left(:, channel);
            a_row = c_right(channel, :) / dt + k_right(channel, :);
            b_row = -c_right(channel, :) / dt;
            gamma = max([norm(a_row, 2), norm(b_row, 2), eps('double')]);
            delay_line_gamma(channel) = gamma;
            delay = delays(channel);
            if delay == 0
                top_input = -(inertial \ shared_left);
                augmented(1:n, 1:n) = ...
                    augmented(1:n, 1:n) + top_input * a_row;
                augmented(1:n, n + (1:n)) = ...
                    augmented(1:n, n + (1:n)) + top_input * b_row;
            else
                % q_r=s_r/gamma是由冻结输入系数唯一决定的对角相似缩放。
                % 它只改善量纲平衡，不改变根、阶数或原差分方程。
                top_input = -(inertial \ shared_left) * gamma;
                buffer_indices = next_buffer_index: ...
                    (next_buffer_index + delay - 1);
                augmented(1:n, buffer_indices(end)) = ...
                    augmented(1:n, buffer_indices(end)) + top_input;
                augmented(buffer_indices(1), 1:n) = a_row / gamma;
                augmented(buffer_indices(1), n + (1:n)) = b_row / gamma;
                if delay > 1
                    augmented(buffer_indices(2:end), ...
                        buffer_indices(1:end-1)) = eye(delay - 1);
                end
                next_buffer_index = next_buffer_index + delay;
            end
        end
        if next_buffer_index ~= expected_order + 1
            error('Board20Step8D:MinimalAugmentationAssemblyMismatch', ...
                '最小增广缓冲区装配未恰好结束于2n+l+j阶。');
        end
        if ~all(isfinite(augmented(:)))
            error('Board20Step8D:NonfiniteMinimalAugmentation', ...
                '最小增广状态矩阵包含非有限数。');
        end
        result.delay_line_gamma = delay_line_gamma;

        [eigenvectors, diagonal] = eig(augmented);
        physical_roots = diag(diagonal);
        if numel(physical_roots) ~= expected_order
            error('Board20Step8D:PhysicalRootCountMismatch', ...
                '最小增广必须返回%d个根，实际为%d个。', ...
                expected_order, numel(physical_roots));
        end
        if any(~isfinite(real(physical_roots)) | ...
                ~isfinite(imag(physical_roots)))
            error('Board20Step8D:NonfinitePhysicalRoot', ...
                '最小增广返回非有限物理根。');
        end
        [~, root_order] = sortrows( ...
            [abs(physical_roots), real(physical_roots), imag(physical_roots)], ...
            [1, 2, 3]);
        physical_roots = physical_roots(root_order);
        eigenvectors = eigenvectors(:, root_order);

        state_residuals = zeros(expected_order, 1);
        polynomial_residuals = zeros(expected_order, 1);
        augmented_norm = norm(augmented, 'fro');
        for root_index = 1:expected_order
            root = physical_roots(root_index);
            state_vector = eigenvectors(:, root_index);
            state_vector_norm = norm(state_vector, 2);
            state_denominator = ...
                (augmented_norm + abs(root)) * state_vector_norm;
            if state_denominator == 0
                state_residuals(root_index) = Inf;
            else
                state_residuals(root_index) = norm( ...
                    augmented * state_vector - root * state_vector, 2) / ...
                    state_denominator;
            end
            physical_vector = state_vector(1:n);
            polynomial_residuals(root_index) = ...
                polynomial_eigenpair_residual( ...
                    polynomial, root, physical_vector);
        end
        result.physical_roots = physical_roots;
        result.state_matrix_relative_residuals = state_residuals;
        result.physical_root_relative_residuals = polynomial_residuals;
        result.minimum_physical_root_magnitude = min(abs(physical_roots));
        result.max_state_matrix_relative_residual = max(state_residuals);
        result.max_polynomial_relative_residual = max(polynomial_residuals);
        if ~(isfinite(result.max_state_matrix_relative_residual) && ...
                result.max_state_matrix_relative_residual <= 1e-8)
            error('Board20Step8D:StateResidualGateFailed', ...
                '最大状态矩阵相对残差%.17g超过固定门1e-8。', ...
                result.max_state_matrix_relative_residual);
        end
        if ~(isfinite(result.max_polynomial_relative_residual) && ...
                result.max_polynomial_relative_residual <= 1e-8)
            error('Board20Step8D:PolynomialResidualGateFailed', ...
                '最大清幂矩阵多项式回代相对残差%.17g超过固定门1e-8。', ...
                result.max_polynomial_relative_residual);
        end

        result.rho = max(abs(physical_roots));
        if ~(isfinite(result.rho) && result.rho > 0)
            error('Board20Step8D:InvalidSpectralRadius', ...
                '谱半径必须有限且大于零，实际为%.17g。', result.rho);
        end
        result.point_status = 'PASS';
        if abs(result.rho - 1) <= 1e-8
            result.stability_class = 'CRITICAL';
        elseif result.rho < 1
            result.stability_class = 'STABLE';
        else
            result.stability_class = 'UNSTABLE';
        end
    catch ME
        result.point_status = 'FAIL';
        result.stability_class = 'FAIL';
        result.failure_identifier = ME.identifier;
        result.failure_message = ME.message;
    end
end


function residual = polynomial_eigenpair_residual(polynomial, root, vector)
    vector_norm = norm(vector, 2);
    if ~(isfinite(vector_norm) && vector_norm > 0)
        residual = Inf;
        return;
    end
    degree = numel(polynomial) - 1;
    terms = complex(zeros(numel(vector), degree + 1));
    denominator_terms = zeros(1, degree + 1);
    root_power = 1;
    for exponent = 0:degree
        terms(:, exponent + 1) = ...
            root_power * (polynomial{exponent + 1} * vector);
        denominator_terms(exponent + 1) = ...
            abs(root_power) * norm(polynomial{exponent + 1}, 'fro') * ...
            vector_norm;
        root_power = root_power * root;
    end
    % 根处各项高度抵消；按项范数从小到大求和，减少固定双精度舍入。
    % 数学对象和分母仍是同一个清幂矩阵多项式后向残差。
    [~, summation_order] = sort(vecnorm(terms, 2, 1), 'ascend');
    value_times_vector = sum(terms(:, summation_order), 2);
    denominator = sum(denominator_terms);
    if denominator == 0
        residual = Inf;
    else
        residual = norm(value_times_vector, 2) / denominator;
    end
end


function coefficients = add_coefficient(coefficients, exponents, exponent, value)
    location = find(exponents == exponent, 1);
    assert(~isempty(location), 'Board20Step8D:InternalExponentRange', ...
        '未分配Laurent指数%d。', exponent);
    coefficients{location} = coefficients{location} + value;
end


function tf = has_exact_nonzero(value)
    tf = any(value(:) ~= 0);
end


function assert_bundle_contract(bundle, bundle_path)
    required = {'division', 'method_index', 'candidate_index', ...
        'route_dimension', 'formula_valid_code', ...
        'paper_grid_eligible_code', 'dt', 'integration_mass_operator', ...
        'C1', 'K1', 'feedback_C', 'feedback_K', ...
        'active_delay_C_left_factor', 'active_delay_C_right_factor', ...
        'active_delay_K_left_factor', 'active_delay_K_right_factor'};
    missing = setdiff(required, fieldnames(bundle), 'stable');
    assert(isempty(missing), 'Board20Step8D:BundleFieldMissing', ...
        '候选包缺字段%s：%s', strjoin(missing, ', '), bundle_path);
end


function value = exact_integer_scalar(raw, field_name, source)
    assert(isnumeric(raw) && isreal(raw) && isscalar(raw) && ...
        isfinite(raw) && raw == fix(raw), ...
        'Board20Step8D:InvalidIntegerScalar', ...
        '%s必须为有限整数标量：%s', field_name, source);
    value = double(raw);
end


function value = exact_binary_scalar(raw, field_name, source)
    value = exact_integer_scalar(raw, field_name, source);
    assert(any(value == [0, 1]), 'Board20Step8D:InvalidBinaryScalar', ...
        '%s必须为0或1：%s', field_name, source);
end


function value = finite_positive_scalar(raw, field_name)
    assert(isnumeric(raw) && isreal(raw) && isscalar(raw) && ...
        isfinite(raw) && raw > 0, 'Board20Step8D:InvalidPositiveScalar', ...
        '%s必须为有限正标量。', field_name);
    value = double(raw);
end


function value = finite_square_matrix(raw, n, field_name)
    value = finite_factor(raw, n, n, field_name);
end


function value = finite_factor(raw, rows, columns, field_name)
    assert(isnumeric(raw) && isreal(raw) && ismatrix(raw) && ...
        isequal(size(raw), [rows, columns]) && all(isfinite(raw(:))), ...
        'Board20Step8D:InvalidMatrix', ...
        '%s必须为有限实数%d-by-%d矩阵。', field_name, rows, columns);
    value = double(raw);
end


function error_value = relative_vector_error(actual, expected)
    denominator = max([norm(actual, 2), norm(expected, 2), eps('double')]);
    error_value = norm(actual - expected, 2) / denominator;
end


function fingerprint = scientific_records_sha256(records)
    digest = java.security.MessageDigest.getInstance('SHA-256');
    digest_update_text(digest, ...
        'board20-step8d-matlab-minimal-augmentation-scientific-records-v1');
    fields = fieldnames(records);
    digest_update_numeric(digest, double(numel(records)));
    for record_index = 1:numel(records)
        digest_update_numeric(digest, double(record_index));
        for field_index = 1:numel(fields)
            field_name = fields{field_index};
            digest_update_text(digest, field_name);
            value = records(record_index).(field_name);
            if ischar(value) || (isstring(value) && isscalar(value))
                digest_update_text(digest, char(string(value)));
            elseif isnumeric(value) || islogical(value)
                digest_update_numeric(digest, value);
            else
                error('Board20Step8D:UnsupportedFingerprintField', ...
                    '科学数组指纹不支持字段%s的类型%s。', ...
                    field_name, class(value));
            end
        end
    end
    raw_digest = typecast(digest.digest(), 'uint8');
    fingerprint = lower(reshape(dec2hex(raw_digest, 2).', 1, []));
end


function digest_update_text(digest, value)
    digest_update_bytes(digest, unicode2native(char(value), 'UTF-8'));
end


function digest_update_numeric(digest, value)
    digest_update_text(digest, class(value));
    digest_update_bytes(digest, typecast(uint64(size(value)), 'uint8'));
    digest_update_bytes(digest, uint8(~isreal(value)));
    if islogical(value)
        digest_update_bytes(digest, uint8(value(:)));
    else
        digest_update_bytes(digest, typecast(real(value(:)), 'uint8'));
        if ~isreal(value)
            digest_update_bytes(digest, typecast(imag(value(:)), 'uint8'));
        end
    end
end


function digest_update_bytes(digest, bytes)
    bytes = uint8(bytes(:));
    length_bytes = typecast(uint64(numel(bytes)), 'uint8');
    digest.update(typecast(length_bytes(:), 'int8'));
    if ~isempty(bytes)
        digest.update(typecast(bytes, 'int8'));
    end
end


function validate_delay(value, field_name)
    assert(isnumeric(value) && isreal(value) && isscalar(value) && ...
        isfinite(value) && value >= 0 && value == fix(value), ...
        'Board20Step8D:InvalidDelay', '%s必须为非负整数。', field_name);
end


function value = method_name(method_index)
    names = {'Original', 'Guyan', 'Craig_Bampton'};
    value = names{method_index};
end


function value = make_bundle_id(division, method_index, candidate_index)
    value = sprintf('D%d_%s_R%02d', division, ...
        method_name(method_index), candidate_index);
end


function signature = point_signature(points_table)
    signature = strjoin(compose('%s:%d:%d', points_table.point_id, ...
        points_table.l_delay, points_table.j_delay), '|');
    signature = char(signature);
end


function record = empty_admission_record()
    record = struct('bundle_id', '', 'division', NaN, ...
        'method_index', NaN, 'method_name', '', 'candidate_id', '', ...
        'route_dimension', NaN, 'formula_valid_code', NaN, ...
        'paper_grid_eligible_code', NaN, 'admission_status', '', ...
        'rejection_reason', '', 'bundle_path', '');
end


function record = empty_package_record()
    record = struct('bundle_path', '', 'bundle', struct(), ...
        'division', NaN, 'method_index', NaN, ...
        'candidate_index', NaN, 'dimension', NaN);
end


function record = empty_result_record()
    record = struct('bundle_id', '', 'division', NaN, ...
        'method_index', NaN, 'method_name', '', 'candidate_id', '', ...
        'route_dimension', NaN, 'point_id', '', 'l_delay', NaN, ...
        'j_delay', NaN, 'rho', NaN, ...
        'expected_physical_root_count', NaN, ...
        'physical_root_count', NaN, ...
        'minimum_physical_root_magnitude', NaN, ...
        'shared_left_max_relative_error', NaN, ...
        'rank_one_force_max_relative_error', NaN, ...
        'delay_line_gamma_1', NaN, 'delay_line_gamma_2', NaN, ...
        'polynomial_degree', NaN, 'clearing_power', NaN, ...
        'minimal_augmented_order', NaN, ...
        'max_state_matrix_relative_residual', NaN, ...
        'max_polynomial_relative_residual', NaN, ...
        'point_status', '', ...
        'stability_class', '', 'failure_identifier', '', ...
        'failure_message', '');
end


function record = empty_scientific_record()
    record = struct('bundle_id', '', 'division', NaN, ...
        'method_index', NaN, 'candidate_index', NaN, ...
        'route_dimension', NaN, 'point_id', '', 'l_delay', NaN, ...
        'j_delay', NaN, 'laurent_exponents', zeros(1, 0), ...
        'laurent_coefficient_frobenius_norms', zeros(1, 0), ...
        'polynomial_degree', NaN, 'clearing_power', NaN, ...
        'expected_physical_root_count', NaN, ...
        'minimal_augmented_order', NaN, ...
        'shared_left_channel_relative_errors', NaN(1, 2), ...
        'rank_one_force_channel_relative_errors', NaN(1, 2), ...
        'delay_line_gamma', NaN(1, 2), ...
        'physical_roots', complex(zeros(0, 1)), ...
        'minimum_physical_root_magnitude', NaN, ...
        'state_matrix_relative_residuals', zeros(0, 1), ...
        'physical_root_relative_residuals', zeros(0, 1), ...
        'rho', NaN, ...
        'max_state_matrix_relative_residual', NaN, ...
        'max_polynomial_relative_residual', NaN, ...
        'point_status', '', 'stability_class', '', ...
        'failure_identifier', '', 'failure_message', '');
end


function result = empty_point_result()
    result = struct('laurent_exponents', zeros(1, 0), ...
        'laurent_coefficient_frobenius_norms', zeros(1, 0), ...
        'polynomial_degree', NaN, 'clearing_power', NaN, ...
        'expected_physical_root_count', NaN, ...
        'minimal_augmented_order', NaN, ...
        'shared_left_channel_relative_errors', NaN(1, 2), ...
        'shared_left_max_relative_error', NaN, ...
        'rank_one_force_channel_relative_errors', NaN(1, 2), ...
        'rank_one_force_max_relative_error', NaN, ...
        'delay_line_gamma', NaN(1, 2), ...
        'physical_roots', complex(zeros(0, 1)), ...
        'minimum_physical_root_magnitude', NaN, ...
        'state_matrix_relative_residuals', zeros(0, 1), ...
        'physical_root_relative_residuals', zeros(0, 1), ...
        'rho', NaN, ...
        'max_state_matrix_relative_residual', NaN, ...
        'max_polynomial_relative_residual', NaN, ...
        'point_status', 'FAIL', 'stability_class', 'FAIL', ...
        'failure_identifier', '', 'failure_message', '');
end


function delete_exact_file_if_present(path_value)
    if isfile(path_value)
        delete(path_value);
    end
end


function write_json_utf8(path_value, value)
    encoded = jsonencode(value, 'PrettyPrint', true);
    file_id = fopen(path_value, 'w', 'n', 'UTF-8');
    assert(file_id >= 0, 'Board20Step8D:JsonOpenFailed', ...
        '无法写入JSON：%s', path_value);
    cleanup = onCleanup(@() fclose(file_id));
    count = fwrite(file_id, encoded, 'char');
    assert(count == strlength(string(encoded)), ...
        'Board20Step8D:JsonWriteFailed', 'JSON未完整写入：%s', path_value);
    clear cleanup;
end
