% 提取时间序列数据
time = simout3.Time;
data_matrix = simout3.Data;

% 创建时间窗选择逻辑索引
time_window = (time >= 13) & (time <= 14);
selected_time = time(time_window);
selected_data = data_matrix(time_window, :);

% 创建局部放大图
figure('Color', 'white', 'Position', [100 100 400 350]);

n = length(selected_time);
interval = round(n / 20);  % 控制标记间隔

% 三条线错开标记索引
idx1 = 1:interval:n;
idx2 = round(interval/3):interval:n;
idx3 = round(2*interval/3):interval:n;

% 边界处理，防止索引越界
idx1(idx1 > n) = [];
idx2(idx2 > n) = [];
idx3(idx3 > n) = [];

% 绘图
%figure('Color', 'white', 'Position', [100 100 400 350]);

h1 = plot(selected_time, selected_data(:,1), ...
    'LineWidth', 1.3, ...
    'LineStyle', '-', ...
    'Color', [0 0.2 0.8], ...
    'Marker', 'o', ...
    'MarkerIndices', idx1, ...
    'MarkerSize', 6, ...
    'MarkerEdgeColor', [0.8 0.1 0.1], ...
    'MarkerFaceColor', 'none', ...
    'DisplayName', 'Origin');

hold on

h2 = plot(selected_time, selected_data(:,2), ...
    'LineWidth', 1.5, ...
    'LineStyle', '-.', ...
    'Color', [0.8 0.1 0.1], ...
    'DisplayName', 'Guyan');

h3 = plot(selected_time, selected_data(:,3), ...
    'LineWidth', 1.5, ...
    'LineStyle', '-.', ...
    'Color', [0.1 0.6 0.2], ...
    'Marker', '^', ...
    'MarkerIndices', idx3, ...
    'MarkerSize', 6, ...
    'MarkerEdgeColor', [0 0.5 0], ...
    'MarkerFaceColor', 'none', ...
    'DisplayName', 'Craig-Bampton');

hold off

% 坐标轴精密调节
ax = gca;
ax.XLim = [13 14];  % 强制设定时间窗
%ax.YLim = [floor(min(selected_data(:))),...
%          ceil(max(selected_data(:)))];
ax.TickDir = 'out';
ax.Box = 'on';

% 标注系统优化
xlabel('时间 (s)', 'FontSize', 12, 'FontName', 'SimHei');
ylabel('响应幅值 (mm)', 'FontSize', 12, 'FontName', 'SimHei');
title('局部时间窗响应分析(13-14秒)', 'FontSize', 13, 'FontName', 'SimHei');

% 智能图例配置
legend([h1, h2, h3],...
    'FontSize', 10,...
    'Location', 'best',...
    'FontName', 'Times New Roman',...
    'EdgeColor', 'none');

% 增强可读性
set(ax, 'Layer', 'top', 'LineWidth', 1.2)
saveas(gcf, 'C:\Users\liangyu\Desktop\新建文件夹 (3)\mode_b_verify_y_10mm_sum2-4.emf','meta');
% 可选：添加时间窗标记线
% line([20 20], ylim, 'Color', [0.5 0.5 0.5], 'LineStyle', '-.', 'LineWidth', 0.8)
% line([25 25], ylim, 'Color', [0.5 0.5 0.5], 'LineStyle', '-.', 'LineWidth', 0.8)