function summary = run_board20_step8e_fullgrid_matlab(execution_mode)
%RUN_BOARD20_STEP8E_FULLGRID_MATLAB 四候选六模型链31x67全网格。
%
% 输入仅为步骤8C索引及其中R01--R04的24个候选MAT。R05/R06在任何
% 网格分配或候选MAT加载前被硬拒绝。本文件独立实现gamma相似缩放的
% 2n+l+j阶标量延迟线最小增广，不调用步骤8D函数，不读取论文边界、
% 历史稳定域掩膜或历史曲线。

    if nargin < 1
        execution_mode = 'sentinel_only';
    end
    execution_mode = validatestring(execution_mode, ...
        {'sentinel_only', 'full'}, mfilename, 'execution_mode');
    script_path = [mfilename('fullpath'), '.m'];
    code_dir = fileparts(script_path);
    board_dir = fileparts(code_dir);
    python_root = fullfile(board_dir, 'outputs', ...
        'step8c_六链模型生成', 'python');
    index_path = fullfile(python_root, '六路线六候选索引.csv');
    output_dir = fullfile(board_dir, 'outputs', ...
        'step8e_四候选全网格', 'matlab');
    assert(isfile(index_path), 'Board20Step8E:IndexMissing', ...
        '缺少步骤8C索引：%s', index_path);
    if ~isfolder(output_dir)
        [made, message] = mkdir(output_dir);
        assert(made, 'Board20Step8E:OutputDirectoryCreateFailed', ...
            '无法创建输出目录%s：%s', output_dir, message);
    end

    paths = struct( ...
        'admission', fullfile(output_dir, 'MATLAB候选准入门禁.csv'), ...
        'sentinel', fullfile(output_dir, 'MATLAB固定性能哨兵.csv'), ...
        'points', fullfile(output_dir, 'MATLAB全网格逐点摘要.csv'), ...
        'certificate', fullfile(output_dir, 'MATLAB边界证书.csv'), ...
        'arrays', fullfile(output_dir, 'MATLAB全网格科学数组.mat'), ...
        'summary', fullfile(output_dir, 'MATLAB步骤8E摘要.json'), ...
        'log', fullfile(output_dir, 'MATLAB步骤8E运行日志.txt'), ...
        'report', fullfile(output_dir, 'MATLAB步骤8E中文报告.md'), ...
        'hashes', fullfile(output_dir, 'MATLAB哈希清单.csv'));
    path_names = fieldnames(paths);
    for path_index = 1:numel(path_names)
        exact_path = paths.(path_names{path_index});
        if isfile(exact_path)
            delete(exact_path);
        end
    end
    log_line(paths.log, sprintf('步骤8E MATLAB开始；execution_mode=%s。', ...
        execution_mode));
    log_line(paths.log, ['输入策略：仅步骤8C索引与R01--R04候选MAT；' ...
        '禁止PDF、论文边界与历史掩膜。']);

    %% 在网格分配和候选MAT加载前完成准入/拒绝硬门。
    index_table = readtable(index_path, 'TextType', 'string', ...
        'VariableNamingRule', 'preserve');
    assert(height(index_table) == 36, 'Board20Step8E:IndexCountMismatch', ...
        '步骤8C索引必须恰有36行，实际为%d。', height(index_table));
    candidate_id = string(index_table.candidate_id);
    eligible_mask = ismember(candidate_id, ["R01", "R02", "R03", "R04"]);
    diagnostic_mask = ismember(candidate_id, ["R05", "R06"]);
    assert(all(eligible_mask | diagnostic_mask), ...
        'Board20Step8E:UnexpectedCandidate', ...
        '步骤8C索引出现R01--R06之外候选。');
    assert(nnz(eligible_mask) == 24 && nnz(diagnostic_mask) == 12, ...
        'Board20Step8E:AdmissionCountMismatch', ...
        '必须准入24个R01--R04并拒绝12个R05/R06。');
    assert(all(index_table.paper_grid_eligible(eligible_mask) == ...
        "ELIGIBLE_SOURCE_COMPLETION"), ...
        'Board20Step8E:EligibleTextMismatch', ...
        'R01--R04必须标记ELIGIBLE_SOURCE_COMPLETION。');
    assert(all(index_table.paper_grid_eligible(diagnostic_mask) == ...
        "BLOCKED_DIAGNOSTIC_ONLY"), ...
        'Board20Step8E:DiagnosticTextMismatch', ...
        'R05/R06必须标记BLOCKED_DIAGNOSTIC_ONLY。');
    assert(all(index_table.formula_status(eligible_mask) == ...
        "FORMULA_COHERENT_SOURCE_COMPLETION"), ...
        'Board20Step8E:EligibleFormulaMismatch', ...
        'R01--R04公式状态不符合准入合同。');
    assert(all(index_table.formula_status(diagnostic_mask) == ...
        "HISTORICAL_DIAGNOSTIC_NOT_FORMULA_VALID"), ...
        'Board20Step8E:DiagnosticFormulaMismatch', ...
        'R05/R06公式状态不符合拒绝合同。');

    admission_status = repmat("REJECTED_DIAGNOSTIC_ONLY", height(index_table), 1);
    admission_status(eligible_mask) = "ACCEPTED_FULL_GRID";
    rejection_reason = repmat( ...
        "R05_R06_HISTORICAL_DIAGNOSTIC_NOT_FORMULA_VALID", ...
        height(index_table), 1);
    rejection_reason(eligible_mask) = "";
    admission_table = table(index_table.bundle_id, candidate_id, ...
        index_table.division, index_table.method, index_table.dimension, ...
        index_table.paper_grid_eligible, index_table.formula_status, ...
        admission_status, rejection_reason, index_table.relative_path, ...
        'VariableNames', {'bundle_id', 'candidate_id', 'division', ...
        'method', 'dimension', 'paper_grid_eligible', 'formula_status', ...
        'admission_status', 'rejection_reason', 'relative_path'});
    writetable(admission_table, paths.admission, 'Encoding', 'UTF-8');
    log_line(paths.log, ...
        '准入门完成：R01--R04共24包；R05/R06共12包已在MAT加载前拒绝。');

    eligible_table = index_table(eligible_mask, :);
    method_order = zeros(height(eligible_table), 1);
    method_order(eligible_table.method == "Original") = 1;
    method_order(eligible_table.method == "Guyan") = 2;
    method_order(eligible_table.method == "Craig_Bampton") = 3;
    assert(all(method_order > 0), 'Board20Step8E:UnknownMethod', ...
        '准入候选包含未知方法。');
    candidate_order = double(extractAfter(eligible_table.candidate_id, 1));
    [~, eligible_order] = sortrows([double(eligible_table.division), ...
        method_order, candidate_order], [1, 2, 3]);
    eligible_table = eligible_table(eligible_order, :);
    method_order = method_order(eligible_order);
    candidate_order = candidate_order(eligible_order);
    expected_route_keys = expected_route_key_list();
    actual_route_keys = compose('D%d_M%d_R%02d', ...
        double(eligible_table.division), method_order, candidate_order);
    assert(isequal(cellstr(actual_route_keys), expected_route_keys), ...
        'Board20Step8E:RouteSortContractMismatch', ...
        '24组路线未满足固定division-method-candidate键排序。');

    %% 拒绝门完成后才加载24个准入MAT并准备独立最小增广合同。
    packages = repmat(empty_package(), 24, 1);
    for package_index = 1:24
        packages(package_index) = load_and_prepare_package( ...
            python_root, eligible_table(package_index, :), ...
            method_order(package_index), candidate_order(package_index));
    end
    assert(numel(unique({packages.bundle_id})) == 24, ...
        'Board20Step8E:DuplicateBundleId', '准入bundle_id不唯一。');
    log_line(paths.log, '24个准入MAT加载并完成共享左向量/秩一/gamma合同门。');

    [parallel_enabled, worker_count] = ensure_parallel_pool();
    log_line(paths.log, sprintf('并行状态：enabled=%d，workers=%d。', ...
        parallel_enabled, worker_count));

    %% 固定性能哨兵：24组各10点，先运行并报告估时。
    sentinel_points = [0, 0; 1, 0; 0, 1; 3, 7; 10, 20; ...
        15, 33; 30, 66; 1, 48; 1, 57; 1, 64];
    sentinel_cells = cell(24, 1);
    sentinel_wall_start = tic;
    if parallel_enabled
        parfor package_index = 1:24
            sentinel_cells{package_index} = compute_sentinels( ...
                packages(package_index), package_index, sentinel_points);
        end
    else
        for package_index = 1:24
            sentinel_cells{package_index} = compute_sentinels( ...
                packages(package_index), package_index, sentinel_points);
        end
    end
    sentinel_wall_seconds = toc(sentinel_wall_start);
    sentinel_records = vertcat(sentinel_cells{:});
    sentinel_table = struct2table(sentinel_records);
    writetable(sentinel_table, paths.sentinel, 'Encoding', 'UTF-8');
    sentinel_pass = all(strcmp({sentinel_records.point_status}, 'PASS'));
    sentinel_state_max = max([sentinel_records.max_state_residual]);
    full_order_cube = expected_full_order_cube(packages);
    sentinel_order_cube = sum([sentinel_records.minimal_order].^3);
    estimated_full_seconds = sentinel_wall_seconds * ...
        full_order_cube / sentinel_order_cube;
    naive_point_scaled_seconds = sentinel_wall_seconds * 49848 / 240;
    log_line(paths.log, sprintf([ ...
        '性能哨兵完成：240/240，PASS=%d，wall=%.6fs，' ...
        '三次方加权估时=%.3fs，点数线性估时=%.3fs，最大状态残差=%.3e。'], ...
        sentinel_pass, sentinel_wall_seconds, estimated_full_seconds, ...
        naive_point_scaled_seconds, sentinel_state_max));
    if ~(sentinel_pass && isfinite(sentinel_state_max) && ...
            sentinel_state_max <= 1e-8)
        error('Board20Step8E:SentinelGateFailed', ...
            '固定性能哨兵未通过1e-8状态残差与有限根门。');
    end
    if strcmp(execution_mode, 'sentinel_only')
        summary = struct( ...
            'execution_mode', execution_mode, ...
            'sentinel_point_count', numel(sentinel_records), ...
            'sentinel_total_root_count', sum([sentinel_records.root_count]), ...
            'sentinel_maximum_state_residual', sentinel_state_max, ...
            'sentinel_wall_seconds', sentinel_wall_seconds, ...
            'estimated_full_seconds_cubic', estimated_full_seconds, ...
            'estimated_full_seconds_linear', naive_point_scaled_seconds, ...
            'sentinel_pass', sentinel_pass);
        log_line(paths.log, ...
            'sentinel_only模式按审计要求停止；未分配或计算完整网格。');
        fprintf(['步骤8E MATLAB哨兵完成：240点，roots=%d，wall=%.6fs，' ...
            '最大状态残差=%.3e；未启动完整网格。\n'], ...
            summary.sentinel_total_root_count, sentinel_wall_seconds, ...
            sentinel_state_max);
        return;
    end

    %% 完整24x31x67网格。
    package_results = cell(24, 1);
    full_wall_start = tic;
    if parallel_enabled
        parfor package_index = 1:24
            package_results{package_index} = compute_package_grid( ...
                packages(package_index), package_index);
        end
    else
        for package_index = 1:24
            package_results{package_index} = compute_package_grid( ...
                packages(package_index), package_index);
        end
    end
    full_wall_seconds = toc(full_wall_start);
    merged = merge_package_results(packages, package_results);
    assert(merged.point_count == 49848, ...
        'Board20Step8E:PointCountMismatch', ...
        '全网格必须恰有49,848点，实际为%d。', merged.point_count);
    assert(merged.total_root_count == 3356432, ...
        'Board20Step8E:RootCountMismatch', ...
        '物理根总数必须恰为3,356,432，实际为%d。', ...
        merged.total_root_count);
    full_gate = all(merged.status_code == 1) && ...
        all(isfinite(merged.root_real)) && all(isfinite(merged.root_imag)) && ...
        all(isfinite(merged.state_residual)) && ...
        max(merged.state_residual) <= 1e-8 && ...
        all(merged.root_count == merged.expected_root_count);
    log_line(paths.log, sprintf([ ...
        '全网格完成：points=%d，roots=%d，wall=%.3fs，' ...
        'max_state_residual=%.3e，gate=%d。'], ...
        merged.point_count, merged.total_root_count, full_wall_seconds, ...
        max(merged.state_residual), full_gate));
    if ~full_gate
        write_point_csv(paths.points, packages, merged);
        save_main_arrays(paths.arrays, packages, merged, struct());
        error('Board20Step8E:FullGridGateFailed', ...
            '全网格存在失败、非有限根、根数错误或状态残差超过1e-8。');
    end

    %% 固定规则自动构造边界证书并对全根做清幂多项式回代。
    [certificate_indices, reason_mask] = ...
        select_certificate_indices(merged);
    certificate_cells = cell(24, 1);
    certificate_wall_start = tic;
    if parallel_enabled
        parfor package_index = 1:24
            package_start = (package_index - 1) * 2077 + 1;
            package_end = package_start + 2076;
            local_mask = certificate_indices >= package_start & ...
                certificate_indices <= package_end;
            local_indices = certificate_indices(local_mask) - package_start + 1;
            global_indices = certificate_indices(local_mask);
            local_reasons = reason_mask(global_indices);
            certificate_cells{package_index} = compute_certificates( ...
                packages(package_index), package_results{package_index}, ...
                local_indices, global_indices, local_reasons);
        end
    else
        for package_index = 1:24
            package_start = (package_index - 1) * 2077 + 1;
            package_end = package_start + 2076;
            local_mask = certificate_indices >= package_start & ...
                certificate_indices <= package_end;
            local_indices = certificate_indices(local_mask) - package_start + 1;
            global_indices = certificate_indices(local_mask);
            local_reasons = reason_mask(global_indices);
            certificate_cells{package_index} = compute_certificates( ...
                packages(package_index), package_results{package_index}, ...
                local_indices, global_indices, local_reasons);
        end
    end
    certificate_wall_seconds = toc(certificate_wall_start);
    certificate = merge_certificate_results(certificate_cells);
    certificate_gate = certificate.count == numel(certificate_indices) && ...
        all(certificate.status_code == 1) && ...
        all(isfinite(certificate.root_real)) && ...
        all(isfinite(certificate.root_imag)) && ...
        all(isfinite(certificate.state_residual)) && ...
        all(isfinite(certificate.polynomial_residual)) && ...
        max(certificate.state_residual) <= 1e-8 && ...
        max(certificate.laurent_residual) <= 1e-8 && ...
        max(certificate.polynomial_residual) <= 1e-8 && ...
        max(certificate.independent_rho_difference) <= 1e-12;
    log_line(paths.log, sprintf([ ...
        '边界证书完成：points=%d，roots=%d，wall=%.3fs，' ...
        'max_laurent_residual=%.3e，max_poly_residual=%.3e，gate=%d。'], ...
        certificate.count, numel(certificate.root_real), ...
        certificate_wall_seconds, max(certificate.laurent_residual), ...
        max(certificate.polynomial_residual), certificate_gate));
    if ~certificate_gate
        error('Board20Step8E:CertificateGateFailed', ...
            '边界证书根数、根匹配或1e-8双残差门未通过。');
    end

    %% 按固定键排序写平面科学数组、逐点CSV与证书CSV。
    write_point_csv(paths.points, packages, merged);
    write_certificate_csv(paths.certificate, packages, merged, certificate);
    scientific_array_sha256 = science_fingerprint(packages, merged, certificate);
    save_main_arrays(paths.arrays, packages, merged, certificate, ...
        scientific_array_sha256);
    point_csv_sha256 = file_sha256(paths.points);
    certificate_csv_sha256 = file_sha256(paths.certificate);

    stable_count = nnz(merged.class_code == 1);
    critical_count = nnz(merged.class_code == 2);
    unstable_count = nnz(merged.class_code == 3);
    summary = struct( ...
        'schema', 'board20-step8e-matlab-fullgrid-v1', ...
        'input_policy', ...
            'ONLY_STEP8C_INDEX_AND_R01_R04_MAT_NO_PDF_NO_MASK', ...
        'solver', 'independent_gamma_scaled_2n_plus_l_plus_j_augmentation', ...
        'key_sort_policy', ...
            'division_method_candidate_l_j; roots_abs_real_imag', ...
        'l_values', 0:30, 'j_values', 0:66, ...
        'admitted_bundle_count', 24, ...
        'rejected_R05_R06_bundle_count', 12, ...
        'point_count', merged.point_count, ...
        'total_physical_root_count', merged.total_root_count, ...
        'expected_total_physical_root_count', 3356432, ...
        'stable_point_count', stable_count, ...
        'critical_point_count', critical_count, ...
        'unstable_point_count', unstable_count, ...
        'maximum_state_matrix_relative_residual', ...
            max(merged.state_residual), ...
        'minimum_physical_root_magnitude', ...
            min(hypot(merged.root_real, merged.root_imag)), ...
        'maximum_physical_root_magnitude', ...
            max(hypot(merged.root_real, merged.root_imag)), ...
        'certificate_point_count', certificate.count, ...
        'certificate_root_count', numel(certificate.root_real), ...
        'certificate_maximum_state_residual', ...
            max(certificate.state_residual), ...
        'certificate_maximum_laurent_residual', ...
            max(certificate.laurent_residual), ...
        'certificate_maximum_polynomial_residual', ...
            max(certificate.polynomial_residual), ...
        'certificate_maximum_independent_rho_difference', ...
            max(certificate.independent_rho_difference), ...
        'certificate_recomputation_contract', ...
            'INDEPENDENT_SECOND_EIG_ROOT_COUNT_AND_RHO_ONLY', ...
        'sentinel_point_count', numel(sentinel_records), ...
        'sentinel_maximum_state_residual', sentinel_state_max, ...
        'dynamic_timing_policy', ...
            'EXCLUDED_FROM_SCIENTIFIC_OUTPUTS_PRESENT_ONLY_IN_RUNTIME_LOG', ...
        'point_csv_sha256', point_csv_sha256, ...
        'certificate_csv_sha256', certificate_csv_sha256, ...
        'scientific_array_sha256', scientific_array_sha256, ...
        'all_points_pass', full_gate, ...
        'certificate_pass', certificate_gate, ...
        'output_files', paths);
    write_report(paths.report, summary);
    write_json_utf8(paths.summary, summary);
    write_hash_manifest(paths.hashes, script_path, index_path, packages, paths);
    log_line(paths.log, sprintf([ ...
        '步骤8E MATLAB完成：points=%d，roots=%d，certificate=%d，' ...
        'science_sha=%s。'], merged.point_count, merged.total_root_count, ...
        certificate.count, scientific_array_sha256));

    fprintf(['步骤8E MATLAB完成：49,848点，3,356,432根，' ...
        '稳定=%d，临界=%d，不稳定=%d，最大状态残差=%.3e，' ...
        '证书点=%d，最大证书多项式残差=%.3e。\n'], ...
        stable_count, critical_count, unstable_count, ...
        summary.maximum_state_matrix_relative_residual, ...
        certificate.count, summary.certificate_maximum_polynomial_residual);
end


function package = load_and_prepare_package(python_root, row, ...
        expected_method_index, expected_candidate_index)
    relative_path = char(row.relative_path);
    mat_path = fullfile(python_root, strrep(relative_path, '/', filesep));
    assert(isfile(mat_path), 'Board20Step8E:EligibleMatMissing', ...
        '准入MAT不存在：%s', mat_path);
    actual_sha = file_sha256(mat_path);
    assert(strcmpi(actual_sha, char(row.mat_sha256)), ...
        'Board20Step8E:EligibleMatHashMismatch', ...
        '准入MAT SHA不符：%s', mat_path);
    required = {'division', 'method_index', 'candidate_index', ...
        'route_dimension', 'formula_valid_code', ...
        'paper_grid_eligible_code', 'dt', 'integration_mass_operator', ...
        'C1', 'K1', 'feedback_C', 'feedback_K', ...
        'active_delay_C_left_factor', 'active_delay_C_right_factor', ...
        'active_delay_K_left_factor', 'active_delay_K_right_factor'};
    loaded = load(mat_path, required{:});
    missing = setdiff(required, fieldnames(loaded), 'stable');
    assert(isempty(missing), 'Board20Step8E:EligibleMatFieldMissing', ...
        '准入MAT缺字段：%s', strjoin(missing, ', '));
    division = exact_integer(loaded.division, 'division');
    method_index = exact_integer(loaded.method_index, 'method_index');
    candidate_index = exact_integer(loaded.candidate_index, 'candidate_index');
    n = exact_integer(loaded.route_dimension, 'route_dimension');
    assert(division == double(row.division) && ...
        method_index == expected_method_index && ...
        candidate_index == expected_candidate_index, ...
        'Board20Step8E:EligibleMatIdentityMismatch', ...
        '准入MAT身份与索引排序合同不符：%s', mat_path);
    assert(candidate_index >= 1 && candidate_index <= 4 && ...
        exact_integer(loaded.formula_valid_code, 'formula_valid_code') == 1 && ...
        exact_integer(loaded.paper_grid_eligible_code, ...
            'paper_grid_eligible_code') == 1, ...
        'Board20Step8E:EligibleMatCodeRejected', ...
        'MAT内部代码不允许进入论文全网格：%s', mat_path);
    dt = finite_positive_scalar(loaded.dt, 'dt');
    mass_operator = finite_matrix(loaded.integration_mass_operator, n, n, ...
        'integration_mass_operator');
    c1 = finite_matrix(loaded.C1, n, n, 'C1');
    k1 = finite_matrix(loaded.K1, n, n, 'K1');
    feedback_c = finite_matrix(loaded.feedback_C, n, n, 'feedback_C');
    feedback_k = finite_matrix(loaded.feedback_K, n, n, 'feedback_K');
    c_left = finite_matrix(loaded.active_delay_C_left_factor, n, 2, ...
        'active_delay_C_left_factor');
    c_right = finite_matrix(loaded.active_delay_C_right_factor, 2, n, ...
        'active_delay_C_right_factor');
    k_left = finite_matrix(loaded.active_delay_K_left_factor, n, 2, ...
        'active_delay_K_left_factor');
    k_right = finite_matrix(loaded.active_delay_K_right_factor, 2, n, ...
        'active_delay_K_right_factor');
    shared_error = zeros(1, 2);
    rank_one_error = zeros(1, 2);
    gamma = zeros(1, 2);
    u = zeros(n, 2);
    a = zeros(2, n);
    b = zeros(2, n);
    for channel = 1:2
        shared_error(channel) = norm(c_left(:, channel) - ...
            k_left(:, channel), 2) / max([norm(c_left(:, channel), 2), ...
            norm(k_left(:, channel), 2), eps('double')]);
        assert(shared_error(channel) <= 1e-12, ...
            'Board20Step8E:SharedLeftGateFailed', ...
            '共享左向量误差超过1e-12：%s channel=%d', ...
            mat_path, channel);
        u(:, channel) = c_left(:, channel);
        a(channel, :) = c_right(channel, :) / dt + k_right(channel, :);
        b(channel, :) = -c_right(channel, :) / dt;
        force_pair = [u(:, channel) * c_right(channel, :), ...
            u(:, channel) * k_right(channel, :)];
        singular_values = svd(force_pair, 'econ');
        if isscalar(singular_values)
            rank_one_error(channel) = 0;
        else
            rank_one_error(channel) = singular_values(2) / singular_values(1);
        end
        assert(isfinite(rank_one_error(channel)) && ...
            rank_one_error(channel) <= 1e-12, ...
            'Board20Step8E:RankOneGateFailed', ...
            '秩一时滞力误差超过1e-12：%s channel=%d', mat_path, channel);
        gamma(channel) = max([norm(a(channel, :), 2), ...
            norm(b(channel, :), 2), eps('double')]);
    end
    inertial = mass_operator / (dt ^ 2);
    assert(rcond(inertial) > eps('double'), ...
        'Board20Step8E:SingularInertialOperator', ...
        'T数值奇异：%s', mat_path);
    b0 = -2 * inertial + c1 / dt + k1 + feedback_c / dt + feedback_k;
    b1 = inertial - c1 / dt - feedback_c / dt;
    package = struct( ...
        'bundle_id', char(row.bundle_id), ...
        'division', division, 'method_index', method_index, ...
        'candidate_index', candidate_index, 'dimension', n, ...
        'method_name', char(row.method), 'dt', dt, ...
        'inertial', inertial, 'b0', b0, 'b1', b1, ...
        'u', u, 'a', a, 'b', b, 'gamma', gamma, ...
        'base_current', -(inertial \ b0), ...
        'base_previous', -(inertial \ b1), ...
        'shared_left_error', shared_error, ...
        'rank_one_error', rank_one_error, ...
        'source_mat_path', mat_path, 'source_mat_sha256', actual_sha);
end


function records = compute_sentinels(package, package_index, points)
    records = repmat(empty_sentinel_record(), size(points, 1), 1);
    for point_index = 1:size(points, 1)
        l_value = points(point_index, 1);
        j_value = points(point_index, 2);
        result = solve_point(package, l_value, j_value, false);
        records(point_index) = struct( ...
            'package_index', package_index, ...
            'bundle_id', package.bundle_id, ...
            'sentinel_id', sprintf('S%02d', point_index - 1), ...
            'l_delay', l_value, 'j_delay', j_value, ...
            'minimal_order', 2 * package.dimension + l_value + j_value, ...
            'rho', result.rho, ...
            'root_count', numel(result.roots), ...
            'max_state_residual', result.max_state_residual, ...
            'point_status', result.status, ...
            'failure_identifier', result.failure_identifier, ...
            'failure_message', result.failure_message);
    end
end


function output = compute_package_grid(package, package_index)
    l_values = repelem((0:30).', 67);
    j_values = repmat((0:66).', 31, 1);
    point_count = numel(l_values);
    expected_count = 2 * package.dimension + l_values + j_values;
    offsets = int64([0; cumsum(int64(expected_count))]);
    total_roots = double(offsets(end));
    roots = complex(NaN(total_roots, 1), NaN(total_roots, 1));
    state_residual = NaN(total_roots, 1);
    rho = NaN(point_count, 1);
    dominant = complex(NaN(point_count, 1), NaN(point_count, 1));
    stable_code = false(point_count, 1);
    critical_code = false(point_count, 1);
    class_code = zeros(point_count, 1, 'int8');
    status_code = zeros(point_count, 1, 'int8');
    root_count = zeros(point_count, 1, 'int32');
    max_state_residual = NaN(point_count, 1);
    failure_identifier = repmat({''}, point_count, 1);
    failure_message = repmat({''}, point_count, 1);
    for point_index = 1:point_count
        result = solve_point(package, l_values(point_index), ...
            j_values(point_index), false);
        first = double(offsets(point_index)) + 1;
        last = double(offsets(point_index + 1));
        if strcmp(result.status, 'PASS') && numel(result.roots) == ...
                expected_count(point_index)
            roots(first:last) = result.roots;
            state_residual(first:last) = result.state_residual;
            rho(point_index) = result.rho;
            dominant(point_index) = result.dominant;
            stable_code(point_index) = result.stable;
            critical_code(point_index) = result.critical;
            class_code(point_index) = result.class_code;
            status_code(point_index) = 1;
            root_count(point_index) = int32(numel(result.roots));
            max_state_residual(point_index) = result.max_state_residual;
        else
            status_code(point_index) = 2;
            failure_identifier{point_index} = result.failure_identifier;
            failure_message{point_index} = result.failure_message;
        end
    end
    output = struct( ...
        'package_index', package_index, ...
        'l_values', int16(l_values), 'j_values', int16(j_values), ...
        'expected_count', int32(expected_count), 'offsets', offsets, ...
        'roots', roots, 'state_residual', state_residual, ...
        'rho', rho, 'dominant', dominant, ...
        'stable_code', stable_code, 'critical_code', critical_code, ...
        'class_code', class_code, 'status_code', status_code, ...
        'root_count', root_count, ...
        'max_state_residual', max_state_residual, ...
        'failure_identifier', {failure_identifier}, ...
        'failure_message', {failure_message});
end


function result = solve_point(package, l_delay, j_delay, compute_polynomial)
    result = empty_point_result();
    try
        n = package.dimension;
        delays = [double(l_delay), double(j_delay)];
        order = 2 * n + sum(delays);
        augmented = zeros(order);
        augmented(1:n, 1:n) = package.base_current;
        augmented(1:n, n + (1:n)) = package.base_previous;
        augmented(n + (1:n), 1:n) = eye(n);
        next_buffer = 2 * n + 1;
        for channel = 1:2
            delay = delays(channel);
            if delay == 0
                input = -(package.inertial \ package.u(:, channel));
                augmented(1:n, 1:n) = augmented(1:n, 1:n) + ...
                    input * package.a(channel, :);
                augmented(1:n, n + (1:n)) = ...
                    augmented(1:n, n + (1:n)) + ...
                    input * package.b(channel, :);
            else
                gamma = package.gamma(channel);
                input = -(package.inertial \ package.u(:, channel)) * gamma;
                buffer = next_buffer:(next_buffer + delay - 1);
                augmented(1:n, buffer(end)) = ...
                    augmented(1:n, buffer(end)) + input;
                augmented(buffer(1), 1:n) = package.a(channel, :) / gamma;
                augmented(buffer(1), n + (1:n)) = ...
                    package.b(channel, :) / gamma;
                if delay > 1
                    augmented(buffer(2:end), buffer(1:end-1)) = eye(delay - 1);
                end
                next_buffer = next_buffer + delay;
            end
        end
        assert(next_buffer == order + 1 && all(isfinite(augmented(:))), ...
            'Board20Step8E:AugmentationAssemblyFailed', ...
            '2n+l+j增广装配或有限性失败。');
        [vectors, diagonal] = eig(augmented);
        roots = diag(diagonal);
        assert(numel(roots) == order && ...
            all(isfinite(real(roots))) && all(isfinite(imag(roots))), ...
            'Board20Step8E:PhysicalRootsInvalid', ...
            '最小增广根数或有限性失败。');
        [~, sort_order] = sortrows([abs(roots), real(roots), imag(roots)], ...
            [1, 2, 3]);
        roots = roots(sort_order);
        vectors = vectors(:, sort_order);
        residual_matrix = augmented * vectors - ...
            vectors .* reshape(roots, 1, []);
        vector_norm = vecnorm(vectors, 2, 1);
        denominator = (norm(augmented, 'fro') + abs(roots).') .* vector_norm;
        state_residual = (vecnorm(residual_matrix, 2, 1) ./ denominator).';
        assert(all(isfinite(state_residual)) && ...
            max(state_residual) <= 1e-8, ...
            'Board20Step8E:StateResidualGateFailed', ...
            '状态矩阵逐根残差超过1e-8或非有限。');
        rho = max(abs(roots));
        dominant_indices = find(abs(roots) == rho);
        dominant = roots(dominant_indices(end));
        stable = rho < 1;
        critical = abs(rho - 1) <= 1e-8;
        if critical
            class_code = int8(2);
        elseif stable
            class_code = int8(1);
        else
            class_code = int8(3);
        end
        laurent_residual = zeros(0, 1);
        polynomial_residual = zeros(0, 1);
        if compute_polynomial
            [polynomial, laurent_exponents, laurent_coefficients] = ...
                build_cleared_polynomial(package, l_delay, j_delay);
            laurent_residual = zeros(order, 1);
            polynomial_residual = zeros(order, 1);
            for root_index = 1:order
                laurent_residual(root_index) = laurent_residual_one( ...
                    laurent_exponents, laurent_coefficients, ...
                    roots(root_index), vectors(1:n, root_index));
                polynomial_residual(root_index) = polynomial_residual_one( ...
                    polynomial, roots(root_index), vectors(1:n, root_index));
            end
            assert(all(isfinite(laurent_residual)) && ...
                max(laurent_residual) <= 1e-8, ...
                'Board20Step8E:LaurentResidualGateFailed', ...
                '证书原Laurent逐根残差超过1e-8或非有限。');
            assert(all(isfinite(polynomial_residual)) && ...
                max(polynomial_residual) <= 1e-8, ...
                'Board20Step8E:PolynomialResidualGateFailed', ...
                '证书清幂矩阵多项式逐根残差超过1e-8或非有限。');
        end
        result = struct('roots', roots, ...
            'state_residual', state_residual, ...
            'laurent_residual', laurent_residual, ...
            'polynomial_residual', polynomial_residual, ...
            'rho', rho, 'dominant', dominant, ...
            'stable', stable, 'critical', critical, ...
            'class_code', class_code, ...
            'max_state_residual', max(state_residual), ...
            'status', 'PASS', 'failure_identifier', '', ...
            'failure_message', '');
    catch ME
        result.failure_identifier = ME.identifier;
        result.failure_message = ME.message;
    end
end


function [polynomial, exponents, coefficients] = ...
        build_cleared_polynomial(package, l_delay, j_delay)
    [exponents, coefficients] = build_laurent_coefficients( ...
        package, l_delay, j_delay);
    clearing = max(0, -exponents(1));
    polynomial = repmat({zeros(package.dimension)}, 1, ...
        max(exponents + clearing) + 1);
    for index = 1:numel(coefficients)
        polynomial{exponents(index) + clearing + 1} = coefficients{index};
    end
    delays = [double(l_delay), double(j_delay)];
    assert(numel(polynomial) - 1 == max(delays) + 2, ...
        'Board20Step8E:PolynomialDegreeMismatch', ...
        '证书清幂矩阵多项式次数不符。');
end


function [exponents, coefficients] = build_laurent_coefficients( ...
        package, l_delay, j_delay)
    n = package.dimension;
    delays = [double(l_delay), double(j_delay)];
    exponents = -(max(delays) + 1):1;
    coefficients = repmat({zeros(n)}, 1, numel(exponents));
    coefficients = add_laurent(coefficients, exponents, 1, package.inertial);
    coefficients = add_laurent(coefficients, exponents, 0, package.b0);
    coefficients = add_laurent(coefficients, exponents, -1, package.b1);
    for channel = 1:2
        coefficients = add_laurent(coefficients, exponents, ...
            -delays(channel), package.u(:, channel) * package.a(channel, :));
        coefficients = add_laurent(coefficients, exponents, ...
            -(delays(channel) + 1), ...
            package.u(:, channel) * package.b(channel, :));
    end
    nonzero = cellfun(@(value) any(value(:) ~= 0), coefficients);
    first = find(nonzero, 1, 'first');
    last = find(nonzero, 1, 'last');
    coefficients = coefficients(first:last);
    exponents = exponents(first:last);
end


function coefficients = add_laurent(coefficients, exponents, exponent, value)
    location = find(exponents == exponent, 1);
    assert(~isempty(location), 'Board20Step8E:LaurentRangeError', ...
        'Laurent指数未分配。');
    coefficients{location} = coefficients{location} + value;
end


function residual = polynomial_residual_one(polynomial, root, vector)
    vector_norm = norm(vector, 2);
    if ~(isfinite(vector_norm) && vector_norm > 0)
        residual = Inf;
        return;
    end
    degree = numel(polynomial) - 1;
    terms = complex(zeros(numel(vector), degree + 1));
    denominator_terms = zeros(1, degree + 1);
    root_power = 1;
    for exponent = 0:degree
        terms(:, exponent + 1) = ...
            root_power * (polynomial{exponent + 1} * vector);
        denominator_terms(exponent + 1) = abs(root_power) * ...
            norm(polynomial{exponent + 1}, 'fro') * vector_norm;
        root_power = root_power * root;
    end
    [~, summation_order] = sort(vecnorm(terms, 2, 1), 'ascend');
    numerator = norm(sum(terms(:, summation_order), 2), 2);
    denominator = sum(denominator_terms);
    if denominator == 0
        residual = Inf;
    else
        residual = numerator / denominator;
    end
end


function residual = laurent_residual_one(exponents, coefficients, root, vector)
% 对原Laurent方程按逐项对数幅值归一化，避免小根的负幂上溢。
    root_abs = abs(root);
    vector_norm = norm(vector, 2);
    if ~(isfinite(root_abs) && root_abs > 0 && ...
            isfinite(vector_norm) && vector_norm > 0)
        residual = Inf;
        return;
    end
    term_count = numel(exponents);
    log_root_abs = log(root_abs);
    root_angle = angle(root);
    denominator_logs = -Inf(1, term_count);
    term_logs = -Inf(1, term_count);
    term_directions = complex(zeros(numel(vector), term_count));
    for index = 1:term_count
        coefficient = coefficients{index};
        coefficient_denominator = norm(coefficient, 'fro') * vector_norm;
        product = coefficient * vector;
        product_norm = norm(product, 2);
        if coefficient_denominator > 0
            denominator_logs(index) = log(coefficient_denominator) + ...
                exponents(index) * log_root_abs;
        end
        if product_norm > 0
            term_logs(index) = log(product_norm) + ...
                exponents(index) * log_root_abs;
            term_directions(:, index) = product / product_norm;
        end
    end
    scale_log = max(denominator_logs);
    if ~isfinite(scale_log)
        residual = Inf;
        return;
    end
    scaled_terms = complex(zeros(numel(vector), term_count));
    for index = 1:term_count
        if isfinite(term_logs(index))
            phase = exp(1i * exponents(index) * root_angle);
            scaled_terms(:, index) = exp(term_logs(index) - scale_log) * ...
                phase * term_directions(:, index);
        end
    end
    [~, summation_order] = sort(vecnorm(scaled_terms, 2, 1), 'ascend');
    numerator = norm(sum(scaled_terms(:, summation_order), 2), 2);
    denominator = sum(exp(denominator_logs - scale_log));
    if ~(isfinite(numerator) && isfinite(denominator) && denominator > 0)
        residual = Inf;
    else
        residual = numerator / denominator;
    end
end


function merged = merge_package_results(packages, results)
    point_count = 24 * 2077;
    total_roots = sum(cellfun(@(value) numel(value.roots), results));
    point_bundle_index = zeros(point_count, 1, 'int16');
    point_l = zeros(point_count, 1, 'int16');
    point_j = zeros(point_count, 1, 'int16');
    expected_root_count = zeros(point_count, 1, 'int32');
    root_count = zeros(point_count, 1, 'int32');
    root_offsets = zeros(point_count + 1, 1, 'int64');
    root_real = NaN(total_roots, 1);
    root_imag = NaN(total_roots, 1);
    state_residual = NaN(total_roots, 1);
    rho = NaN(point_count, 1);
    dominant_real = NaN(point_count, 1);
    dominant_imag = NaN(point_count, 1);
    stable_code = false(point_count, 1);
    critical_code = false(point_count, 1);
    class_code = zeros(point_count, 1, 'int8');
    status_code = zeros(point_count, 1, 'int8');
    max_state_residual = NaN(point_count, 1);
    gamma1 = NaN(point_count, 1);
    gamma2 = NaN(point_count, 1);
    failure_identifier = repmat({''}, point_count, 1);
    failure_message = repmat({''}, point_count, 1);
    root_base = int64(0);
    for package_index = 1:24
        point_first = (package_index - 1) * 2077 + 1;
        point_last = point_first + 2076;
        point_range = point_first:point_last;
        result = results{package_index};
        local_root_count = numel(result.roots);
        root_range = double(root_base) + (1:local_root_count);
        point_bundle_index(point_range) = int16(package_index);
        point_l(point_range) = result.l_values;
        point_j(point_range) = result.j_values;
        expected_root_count(point_range) = result.expected_count;
        root_count(point_range) = result.root_count;
        root_offsets(point_first:point_last + 1) = ...
            root_base + result.offsets;
        root_real(root_range) = real(result.roots);
        root_imag(root_range) = imag(result.roots);
        state_residual(root_range) = result.state_residual;
        rho(point_range) = result.rho;
        dominant_real(point_range) = real(result.dominant);
        dominant_imag(point_range) = imag(result.dominant);
        stable_code(point_range) = result.stable_code;
        critical_code(point_range) = result.critical_code;
        class_code(point_range) = result.class_code;
        status_code(point_range) = result.status_code;
        max_state_residual(point_range) = result.max_state_residual;
        gamma1(point_range) = packages(package_index).gamma(1);
        gamma2(point_range) = packages(package_index).gamma(2);
        failure_identifier(point_range) = result.failure_identifier;
        failure_message(point_range) = result.failure_message;
        root_base = root_base + int64(local_root_count);
    end
    merged = struct( ...
        'point_count', point_count, 'total_root_count', double(root_base), ...
        'point_bundle_index', point_bundle_index, ...
        'point_l', point_l, 'point_j', point_j, ...
        'expected_root_count', expected_root_count, ...
        'root_count', root_count, 'root_offsets', root_offsets, ...
        'root_real', root_real, 'root_imag', root_imag, ...
        'state_residual', state_residual, 'rho', rho, ...
        'dominant_real', dominant_real, 'dominant_imag', dominant_imag, ...
        'stable_code', stable_code, 'critical_code', critical_code, ...
        'class_code', class_code, 'status_code', status_code, ...
        'max_state_residual', max_state_residual, ...
        'gamma1', gamma1, 'gamma2', gamma2, ...
        'failure_identifier', {failure_identifier}, ...
        'failure_message', {failure_message});
end


function [indices, reason_mask] = select_certificate_indices(merged)
    reason_mask = zeros(merged.point_count, 1, 'uint8');
    for package_index = 1:24
        first = (package_index - 1) * 2077 + 1;
        last = first + 2076;
        class_grid = reshape(merged.class_code(first:last), [67, 31]).';
        rho_grid = reshape(merged.rho(first:last), [67, 31]).';
        local_reason = zeros(2077, 1, 'uint8');
        [rows_h, columns_h] = find( ...
            class_grid(:, 1:end-1) ~= class_grid(:, 2:end));
        horizontal_left = (rows_h - 1) * 67 + columns_h;
        horizontal_right = horizontal_left + 1;
        local_reason(horizontal_left) = bitor( ...
            local_reason(horizontal_left), uint8(1));
        local_reason(horizontal_right) = bitor( ...
            local_reason(horizontal_right), uint8(1));
        [rows_v, columns_v] = find( ...
            class_grid(1:end-1, :) ~= class_grid(2:end, :));
        vertical_top = (rows_v - 1) * 67 + columns_v;
        vertical_bottom = vertical_top + 67;
        local_reason(vertical_top) = bitor( ...
            local_reason(vertical_top), uint8(1));
        local_reason(vertical_bottom) = bitor( ...
            local_reason(vertical_bottom), uint8(1));
        distance = abs(rho_grid - 1);
        for row = 1:31
            minimum = min(distance(row, :));
            columns = find(distance(row, :) == minimum);
            local = (row - 1) * 67 + columns;
            local_reason(local) = bitor(local_reason(local), uint8(2));
        end
        for column = 1:67
            minimum = min(distance(:, column));
            rows = find(distance(:, column) == minimum);
            local = (rows - 1) * 67 + column;
            local_reason(local) = bitor(local_reason(local), uint8(4));
        end
        reason_mask(first:last) = local_reason;
    end
    indices = find(reason_mask > 0);
end


function output = compute_certificates(package, package_result, ...
        local_indices, global_indices, reasons)
    count = numel(local_indices);
    root_counts = double(package_result.expected_count(local_indices));
    offsets = int64([0; cumsum(int64(root_counts))]);
    total_roots = double(offsets(end));
    root_real = NaN(total_roots, 1);
    root_imag = NaN(total_roots, 1);
    state_residual = NaN(total_roots, 1);
    laurent_residual = NaN(total_roots, 1);
    polynomial_residual = NaN(total_roots, 1);
    status_code = zeros(count, 1, 'int8');
    independent_rho_difference = NaN(count, 1);
    max_laurent_residual = NaN(count, 1);
    max_polynomial_residual = NaN(count, 1);
    for certificate_index = 1:count
        local = local_indices(certificate_index);
        l_value = double(package_result.l_values(local));
        j_value = double(package_result.j_values(local));
        result = solve_point(package, l_value, j_value, true);
        first = double(offsets(certificate_index)) + 1;
        last = double(offsets(certificate_index + 1));
        reference_rho = package_result.rho(local);
        if strcmp(result.status, 'PASS') && numel(result.roots) == ...
                root_counts(certificate_index)
            root_real(first:last) = real(result.roots);
            root_imag(first:last) = imag(result.roots);
            state_residual(first:last) = result.state_residual;
            laurent_residual(first:last) = result.laurent_residual;
            polynomial_residual(first:last) = result.polynomial_residual;
            independent_rho_difference(certificate_index) = ...
                abs(result.rho - reference_rho);
            max_laurent_residual(certificate_index) = ...
                max(result.laurent_residual);
            max_polynomial_residual(certificate_index) = ...
                max(result.polynomial_residual);
            if independent_rho_difference(certificate_index) <= 1e-12
                status_code(certificate_index) = 1;
            else
                status_code(certificate_index) = 2;
            end
        else
            status_code(certificate_index) = 2;
        end
    end
    output = struct( ...
        'global_point_indices', int32(global_indices), ...
        'local_point_indices', int32(local_indices), ...
        'reason_mask', uint8(reasons), 'offsets', offsets, ...
        'root_real', root_real, 'root_imag', root_imag, ...
        'state_residual', state_residual, ...
        'laurent_residual', laurent_residual, ...
        'polynomial_residual', polynomial_residual, ...
        'status_code', status_code, ...
        'independent_rho_difference', independent_rho_difference, ...
        'max_laurent_residual', max_laurent_residual, ...
        'max_polynomial_residual', max_polynomial_residual);
end


function certificate = merge_certificate_results(results)
    count = sum(cellfun(@(value) numel(value.global_point_indices), results));
    total_roots = sum(cellfun(@(value) numel(value.root_real), results));
    global_indices = zeros(count, 1, 'int32');
    reason_mask = zeros(count, 1, 'uint8');
    offsets = zeros(count + 1, 1, 'int64');
    root_real = NaN(total_roots, 1);
    root_imag = NaN(total_roots, 1);
    state_residual = NaN(total_roots, 1);
    laurent_residual = NaN(total_roots, 1);
    polynomial_residual = NaN(total_roots, 1);
    status_code = zeros(count, 1, 'int8');
    independent_rho_difference = NaN(count, 1);
    max_laurent_residual = NaN(count, 1);
    max_polynomial_residual = NaN(count, 1);
    point_base = 0;
    root_base = int64(0);
    for package_index = 1:24
        result = results{package_index};
        local_count = numel(result.global_point_indices);
        local_roots = numel(result.root_real);
        point_range = point_base + (1:local_count);
        root_range = double(root_base) + (1:local_roots);
        global_indices(point_range) = result.global_point_indices;
        reason_mask(point_range) = result.reason_mask;
        offsets(point_base + 1:point_base + local_count + 1) = ...
            root_base + result.offsets;
        root_real(root_range) = result.root_real;
        root_imag(root_range) = result.root_imag;
        state_residual(root_range) = result.state_residual;
        laurent_residual(root_range) = result.laurent_residual;
        polynomial_residual(root_range) = result.polynomial_residual;
        status_code(point_range) = result.status_code;
        independent_rho_difference(point_range) = ...
            result.independent_rho_difference;
        max_laurent_residual(point_range) = result.max_laurent_residual;
        max_polynomial_residual(point_range) = result.max_polynomial_residual;
        point_base = point_base + local_count;
        root_base = root_base + int64(local_roots);
    end
    assert(issorted(global_indices), ...
        'Board20Step8E:CertificateSortMismatch', ...
        '证书点未按全局固定键排序。');
    certificate = struct( ...
        'count', count, 'global_point_indices', global_indices, ...
        'reason_mask', reason_mask, 'offsets', offsets, ...
        'root_real', root_real, 'root_imag', root_imag, ...
        'state_residual', state_residual, ...
        'laurent_residual', laurent_residual, ...
        'polynomial_residual', polynomial_residual, ...
        'status_code', status_code, ...
        'independent_rho_difference', independent_rho_difference, ...
        'max_laurent_residual', max_laurent_residual, ...
        'max_polynomial_residual', max_polynomial_residual);
end


function write_point_csv(path_value, packages, merged)
    point_index = int32((1:merged.point_count).');
    bundle_id = string({packages(merged.point_bundle_index).bundle_id}).';
    division = int8([packages(merged.point_bundle_index).division].');
    method_index = int8([packages(merged.point_bundle_index).method_index].');
    candidate_index = int8([packages(merged.point_bundle_index).candidate_index].');
    route_dimension = int16([packages(merged.point_bundle_index).dimension].');
    root_offset_zero_based = merged.root_offsets(1:end-1);
    class_name = repmat("", merged.point_count, 1);
    class_name(merged.class_code == 1) = "STABLE";
    class_name(merged.class_code == 2) = "CRITICAL";
    class_name(merged.class_code == 3) = "UNSTABLE";
    point_status = repmat("FAIL", merged.point_count, 1);
    point_status(merged.status_code == 1) = "PASS";
    output = table(point_index, bundle_id, division, method_index, ...
        candidate_index, route_dimension, merged.point_l, merged.point_j, ...
        root_offset_zero_based, merged.root_count, ...
        merged.expected_root_count, merged.gamma1, merged.gamma2, ...
        merged.rho, merged.dominant_real, merged.dominant_imag, ...
        merged.stable_code, merged.critical_code, merged.class_code, ...
        class_name, merged.max_state_residual, point_status, ...
        string(merged.failure_identifier), string(merged.failure_message), ...
        'VariableNames', {'point_index', 'bundle_id', 'division', ...
        'method_index', 'candidate_index', 'route_dimension', 'l_delay', ...
        'j_delay', 'root_offset_zero_based', 'root_count', ...
        'expected_root_count', 'gamma_1', 'gamma_2', 'rho', ...
        'dominant_real', 'dominant_imag', 'stable', 'critical', ...
        'class_code', 'class_name', 'max_state_residual', ...
        'point_status', 'failure_identifier', 'failure_message'});
    writetable(output, path_value, 'Encoding', 'UTF-8');
end


function write_certificate_csv(path_value, packages, merged, certificate)
    point_index = certificate.global_point_indices;
    source = double(point_index);
    bundle_index = merged.point_bundle_index(source);
    bundle_id = string({packages(bundle_index).bundle_id}).';
    l_delay = merged.point_l(source);
    j_delay = merged.point_j(source);
    reason_mask = certificate.reason_mask;
    adjacent_change_endpoint = bitand(reason_mask, uint8(1)) > 0;
    row_minimum_abs_rho_minus_one = bitand(reason_mask, uint8(2)) > 0;
    column_minimum_abs_rho_minus_one = bitand(reason_mask, uint8(4)) > 0;
    certificate_root_offset_zero_based = certificate.offsets(1:end-1);
    root_count = int32(diff(certificate.offsets));
    rho = merged.rho(source);
    class_code = merged.class_code(source);
    output = table(point_index, bundle_id, l_delay, j_delay, reason_mask, ...
        adjacent_change_endpoint, row_minimum_abs_rho_minus_one, ...
        column_minimum_abs_rho_minus_one, ...
        certificate_root_offset_zero_based, root_count, rho, class_code, ...
        certificate.independent_rho_difference, ...
        certificate.max_laurent_residual, ...
        certificate.max_polynomial_residual, certificate.status_code, ...
        'VariableNames', {'point_index', 'bundle_id', 'l_delay', ...
        'j_delay', 'reason_mask', 'adjacent_change_endpoint', ...
        'row_minimum_abs_rho_minus_one', ...
        'column_minimum_abs_rho_minus_one', ...
        'certificate_root_offset_zero_based', 'root_count', 'rho', ...
        'class_code', 'independent_recompute_rho_abs_difference', ...
        'max_laurent_residual', 'max_polynomial_residual', 'status_code'});
    writetable(output, path_value, 'Encoding', 'UTF-8');
end


function save_main_arrays(path_value, packages, merged, certificate, varargin)
    schema = 'board20-step8e-matlab-flat-arrays-v1';
    key_sort_contract = 'division_method_candidate_l_j; roots_abs_real_imag';
    root_offset_contract = 'zero_based_half_open_offsets_length_point_count_plus_1';
    route_bundle_id = {packages.bundle_id}.';
    route_division = int8([packages.division].');
    route_method_index = int8([packages.method_index].');
    route_candidate_index = int8([packages.candidate_index].');
    route_dimension = int16([packages.dimension].');
    route_gamma = vertcat(packages.gamma);
    route_source_mat_path = {packages.source_mat_path}.';
    route_source_mat_sha256 = {packages.source_mat_sha256}.';
    point_bundle_index = merged.point_bundle_index;
    point_l = merged.point_l;
    point_j = merged.point_j;
    point_expected_root_count = merged.expected_root_count;
    point_root_count = merged.root_count;
    point_root_offsets = merged.root_offsets;
    root_real = merged.root_real;
    root_imag = merged.root_imag;
    root_state_relative_residual = merged.state_residual;
    point_rho = merged.rho;
    point_dominant_real = merged.dominant_real;
    point_dominant_imag = merged.dominant_imag;
    point_stable_code = merged.stable_code;
    point_critical_code = merged.critical_code;
    point_class_code = merged.class_code;
    point_status_code = merged.status_code;
    point_max_state_relative_residual = merged.max_state_residual;
    point_gamma_1 = merged.gamma1;
    point_gamma_2 = merged.gamma2;
    point_failure_identifier = merged.failure_identifier;
    point_failure_message = merged.failure_message;
    save_arguments = {'schema', 'key_sort_contract', 'root_offset_contract', ...
        'route_bundle_id', 'route_division', 'route_method_index', ...
        'route_candidate_index', 'route_dimension', 'route_gamma', ...
        'route_source_mat_path', 'route_source_mat_sha256', ...
        'point_bundle_index', 'point_l', 'point_j', ...
        'point_expected_root_count', 'point_root_count', ...
        'point_root_offsets', 'root_real', 'root_imag', ...
        'root_state_relative_residual', 'point_rho', ...
        'point_dominant_real', 'point_dominant_imag', ...
        'point_stable_code', 'point_critical_code', 'point_class_code', ...
        'point_status_code', 'point_max_state_relative_residual', ...
        'point_gamma_1', 'point_gamma_2', 'point_failure_identifier', ...
        'point_failure_message'};
    if isstruct(certificate) && isfield(certificate, 'count')
        certificate_point_indices = certificate.global_point_indices;
        certificate_reason_mask = certificate.reason_mask;
        certificate_root_offsets = certificate.offsets;
        certificate_root_real = certificate.root_real;
        certificate_root_imag = certificate.root_imag;
        certificate_root_state_relative_residual = certificate.state_residual;
        certificate_root_laurent_relative_residual = ...
            certificate.laurent_residual;
        certificate_root_polynomial_relative_residual = ...
            certificate.polynomial_residual;
        certificate_status_code = certificate.status_code;
        certificate_independent_rho_difference = ...
            certificate.independent_rho_difference;
        certificate_max_laurent_relative_residual = ...
            certificate.max_laurent_residual;
        certificate_max_polynomial_relative_residual = ...
            certificate.max_polynomial_residual;
        save_arguments = [save_arguments, { ...
            'certificate_point_indices', 'certificate_reason_mask', ...
            'certificate_root_offsets', 'certificate_root_real', ...
            'certificate_root_imag', ...
            'certificate_root_state_relative_residual', ...
            'certificate_root_laurent_relative_residual', ...
            'certificate_root_polynomial_relative_residual', ...
            'certificate_status_code', ...
            'certificate_independent_rho_difference', ...
            'certificate_max_laurent_relative_residual', ...
            'certificate_max_polynomial_relative_residual'}]; %#ok<AGROW>
    end
    if ~isempty(varargin)
        scientific_array_sha256 = varargin{1};
        save_arguments{end + 1} = 'scientific_array_sha256';
    end
    save(path_value, save_arguments{:}, '-v7.3');
end


function fingerprint = science_fingerprint(packages, merged, certificate)
    digest = java.security.MessageDigest.getInstance('SHA-256');
    digest_text(digest, 'board20-step8e-matlab-scientific-flat-arrays-v1');
    for package_index = 1:24
        digest_text(digest, packages(package_index).bundle_id);
        digest_numeric(digest, [packages(package_index).division, ...
            packages(package_index).method_index, ...
            packages(package_index).candidate_index, ...
            packages(package_index).dimension]);
        digest_numeric(digest, packages(package_index).gamma);
        digest_text(digest, packages(package_index).source_mat_sha256);
    end
    fixed_arrays = {merged.point_bundle_index, merged.point_l, merged.point_j, ...
        merged.expected_root_count, merged.root_count, merged.root_offsets, ...
        merged.root_real, merged.root_imag, merged.state_residual, ...
        merged.rho, merged.dominant_real, merged.dominant_imag, ...
        merged.stable_code, merged.critical_code, merged.class_code, ...
        merged.status_code, merged.max_state_residual, ...
        merged.gamma1, merged.gamma2, ...
        certificate.global_point_indices, certificate.reason_mask, ...
        certificate.offsets, certificate.root_real, certificate.root_imag, ...
        certificate.state_residual, certificate.laurent_residual, ...
        certificate.polynomial_residual, certificate.status_code, ...
        certificate.independent_rho_difference, ...
        certificate.max_laurent_residual, ...
        certificate.max_polynomial_residual};
    for array_index = 1:numel(fixed_arrays)
        digest_numeric(digest, fixed_arrays{array_index});
    end
    raw = typecast(digest.digest(), 'uint8');
    fingerprint = lower(reshape(dec2hex(raw, 2).', 1, []));
end


function write_report(path_value, summary)
    lines = { ...
        '# 板块20步骤8E MATLAB四候选全网格报告', '', ...
        '## 输入与准入', '', ...
        '- 只读取步骤8C索引与R01--R04的24个候选MAT。', ...
        '- R05/R06共12包在任何网格分配和候选MAT加载前拒绝。', ...
        '- 未读取论文边界、历史稳定域掩膜或历史曲线。', '', ...
        '## 计算结果', '', ...
        sprintf('- 网格点：%d。', summary.point_count), ...
        sprintf('- 全部物理根：%d。', summary.total_physical_root_count), ...
        sprintf('- 稳定/临界/不稳定：%d / %d / %d。', ...
            summary.stable_point_count, summary.critical_point_count, ...
            summary.unstable_point_count), ...
        sprintf('- 最大状态矩阵相对残差：%.17g。', ...
            summary.maximum_state_matrix_relative_residual), ...
        '', ...
        '## 自动边界证书', '', ...
        sprintf('- 证书点：%d；证书根：%d。', ...
            summary.certificate_point_count, summary.certificate_root_count), ...
        sprintf('- 最大清幂矩阵多项式残差：%.17g。', ...
            summary.certificate_maximum_polynomial_residual), ...
        sprintf('- 最大原Laurent相对残差：%.17g。', ...
            summary.certificate_maximum_laurent_residual), ...
        '- 证书由第二次独立eig重算；自检只比较根数和谱半径，不逐项配对根。', ...
        '- 规则：相邻分类变化两端；每行及每列|rho-1|最小点，并列全收。', '', ...
        '## 确定性标识', '', ...
        sprintf('- 规范化科学数组SHA-256：`%s`。', ...
            summary.scientific_array_sha256), ...
        sprintf('- 逐点CSV SHA-256：`%s`。', summary.point_csv_sha256)};
    write_text_utf8(path_value, strjoin(lines, newline));
end


function write_hash_manifest(path_value, script_path, index_path, packages, paths)
    roles = {'main_script'; 'step8c_index'};
    file_paths = {script_path; index_path};
    determinism_scope = {'DETERMINISTIC_INPUT'; 'DETERMINISTIC_INPUT'};
    for package_index = 1:24
        roles{end + 1, 1} = sprintf('eligible_mat_%02d', package_index); %#ok<AGROW>
        file_paths{end + 1, 1} = packages(package_index).source_mat_path; %#ok<AGROW>
        determinism_scope{end + 1, 1} = 'DETERMINISTIC_INPUT'; %#ok<AGROW>
    end
    output_fields = {'admission', 'sentinel', 'points', 'certificate', ...
        'arrays', 'summary', 'report'};
    for index = 1:numel(output_fields)
        roles{end + 1, 1} = ['output_', output_fields{index}]; %#ok<AGROW>
        file_paths{end + 1, 1} = paths.(output_fields{index}); %#ok<AGROW>
        if strcmp(output_fields{index}, 'arrays')
            determinism_scope{end + 1, 1} = ...
                'HDF5_CONTAINER_BYTES_EXCLUDED_USE_SCIENTIFIC_ARRAY_SHA'; %#ok<AGROW>
        else
            determinism_scope{end + 1, 1} = 'DETERMINISTIC_OUTPUT'; %#ok<AGROW>
        end
    end
    sha256 = cellfun(@file_sha256, file_paths, 'UniformOutput', false);
    bytes = cellfun(@file_bytes, file_paths);
    table_value = table(string(roles), string(file_paths), string(sha256), ...
        bytes(:), string(determinism_scope), ...
        'VariableNames', {'role', 'path', 'sha256', 'bytes', ...
        'determinism_scope'});
    writetable(table_value, path_value, 'Encoding', 'UTF-8');
end


function bytes = file_bytes(path_value)
    information = dir(path_value);
    assert(isscalar(information), 'Board20Step8E:FileBytesLookupFailed', ...
        '无法唯一读取文件大小：%s', path_value);
    bytes = information.bytes;
end


function [enabled, workers] = ensure_parallel_pool()
    enabled = false;
    workers = 1;
    if ~(license('test', 'Distrib_Computing_Toolbox') && ...
            ~isempty(ver('parallel')))
        return;
    end
    try
        pool = gcp('nocreate');
        if isempty(pool)
            workers_requested = min(8, feature('numcores'));
            pool = parpool('threads', workers_requested);
        end
        enabled = true;
        workers = pool.NumWorkers;
    catch
        enabled = false;
        workers = 1;
    end
end


function value = expected_full_order_cube(packages)
    value = 0;
    for package_index = 1:24
        n = packages(package_index).dimension;
        for l_value = 0:30
            for j_value = 0:66
                value = value + (2 * n + l_value + j_value)^3;
            end
        end
    end
end


function keys = expected_route_key_list()
    keys = cell(24, 1);
    index = 0;
    for division = 1:2
        for method = 1:3
            for candidate = 1:4
                index = index + 1;
                keys{index} = sprintf('D%d_M%d_R%02d', ...
                    division, method, candidate);
            end
        end
    end
end


function package = empty_package()
    package = struct('bundle_id', '', 'division', NaN, ...
        'method_index', NaN, 'candidate_index', NaN, 'dimension', NaN, ...
        'method_name', '', 'dt', NaN, 'inertial', zeros(0), ...
        'b0', zeros(0), 'b1', zeros(0), 'u', zeros(0, 2), ...
        'a', zeros(2, 0), 'b', zeros(2, 0), 'gamma', NaN(1, 2), ...
        'base_current', zeros(0), 'base_previous', zeros(0), ...
        'shared_left_error', NaN(1, 2), 'rank_one_error', NaN(1, 2), ...
        'source_mat_path', '', 'source_mat_sha256', '');
end


function record = empty_sentinel_record()
    record = struct('package_index', NaN, 'bundle_id', '', ...
        'sentinel_id', '', 'l_delay', NaN, 'j_delay', NaN, ...
        'minimal_order', NaN, 'rho', NaN, ...
        'root_count', NaN, 'max_state_residual', NaN, ...
        'point_status', 'FAIL', 'failure_identifier', '', ...
        'failure_message', '');
end


function result = empty_point_result()
    result = struct('roots', complex(zeros(0, 1)), ...
        'state_residual', zeros(0, 1), ...
        'laurent_residual', zeros(0, 1), ...
        'polynomial_residual', zeros(0, 1), ...
        'rho', NaN, 'dominant', complex(NaN, NaN), ...
        'stable', false, 'critical', false, 'class_code', int8(0), ...
        'max_state_residual', NaN, 'status', 'FAIL', ...
        'failure_identifier', '', 'failure_message', '');
end


function value = exact_integer(raw, name)
    assert(isnumeric(raw) && isreal(raw) && isscalar(raw) && ...
        isfinite(raw) && raw == fix(raw), 'Board20Step8E:InvalidInteger', ...
        '%s必须为有限整数标量。', name);
    value = double(raw);
end


function value = finite_positive_scalar(raw, name)
    assert(isnumeric(raw) && isreal(raw) && isscalar(raw) && ...
        isfinite(raw) && raw > 0, 'Board20Step8E:InvalidPositiveScalar', ...
        '%s必须为有限正标量。', name);
    value = double(raw);
end


function value = finite_matrix(raw, rows, columns, name)
    assert(isnumeric(raw) && isreal(raw) && ...
        isequal(size(raw), [rows, columns]) && all(isfinite(raw(:))), ...
        'Board20Step8E:InvalidMatrix', ...
        '%s必须为有限实数%d-by-%d矩阵。', name, rows, columns);
    value = double(raw);
end


function log_line(path_value, message)
    file_id = fopen(path_value, 'a', 'n', 'UTF-8');
    assert(file_id >= 0, 'Board20Step8E:LogOpenFailed', ...
        '无法写入日志：%s', path_value);
    cleanup = onCleanup(@() fclose(file_id));
    fprintf(file_id, '%s | %s\n', char(datetime('now', ...
        'Format', 'yyyy-MM-dd HH:mm:ss.SSS')), message);
    clear cleanup;
end


function hash_value = file_sha256(path_value)
    file_id = fopen(path_value, 'rb');
    assert(file_id >= 0, 'Board20Step8E:HashOpenFailed', ...
        '无法读取待哈希文件：%s', path_value);
    cleanup = onCleanup(@() fclose(file_id));
    digest = java.security.MessageDigest.getInstance('SHA-256');
    while true
        bytes = fread(file_id, 1024 * 1024, '*uint8');
        if isempty(bytes)
            break;
        end
        digest.update(typecast(bytes(:), 'int8'));
    end
    raw = typecast(digest.digest(), 'uint8');
    hash_value = upper(reshape(dec2hex(raw, 2).', 1, []));
    clear cleanup;
end


function digest_text(digest, value)
    digest_bytes(digest, unicode2native(char(value), 'UTF-8'));
end


function digest_numeric(digest, value)
    digest_text(digest, class(value));
    digest_bytes(digest, typecast(uint64(size(value)), 'uint8'));
    digest_bytes(digest, uint8(~isreal(value)));
    if islogical(value)
        digest_bytes(digest, uint8(value(:)));
    else
        digest_bytes(digest, typecast(real(value(:)), 'uint8'));
        if ~isreal(value)
            digest_bytes(digest, typecast(imag(value(:)), 'uint8'));
        end
    end
end


function digest_bytes(digest, bytes)
    bytes = uint8(bytes(:));
    digest.update(typecast(typecast(uint64(numel(bytes)), 'uint8'), 'int8'));
    if ~isempty(bytes)
        digest.update(typecast(bytes, 'int8'));
    end
end


function write_json_utf8(path_value, value)
    write_text_utf8(path_value, jsonencode(value, 'PrettyPrint', true));
end


function write_text_utf8(path_value, text_value)
    file_id = fopen(path_value, 'w', 'n', 'UTF-8');
    assert(file_id >= 0, 'Board20Step8E:TextOpenFailed', ...
        '无法写入文本：%s', path_value);
    cleanup = onCleanup(@() fclose(file_id));
    count = fwrite(file_id, text_value, 'char');
    assert(count == strlength(string(text_value)), ...
        'Board20Step8E:TextWriteFailed', '文本未完整写入：%s', path_value);
    clear cleanup;
end
